// ============================================================
// LV MATERIALS KNOWLEDGE BASE — 200+ items per system
// Used as AI reference for floorplan takeoff analysis
// Labor hours from NECA Electrical Labor Book
// ============================================================

export interface MaterialItem {
    name: string;
    labor_hours_per_unit: number;
    system: string;
    category: string;
}

// ============================================================
// 1. STRUCTURED CABLING
// ============================================================
const STRUCTURED_CABLING: MaterialItem[] = [
    // --- Copper Cable ---
    { name: 'Cat5e Plenum Cable (1000ft)', labor_hours_per_unit: 4, system: 'STRUCTURED CABLING', category: 'Cable' },
    { name: 'Cat6 Plenum Cable (1000ft)', labor_hours_per_unit: 5, system: 'STRUCTURED CABLING', category: 'Cable' },
    { name: 'Cat6 Riser Cable (1000ft)', labor_hours_per_unit: 4.5, system: 'STRUCTURED CABLING', category: 'Cable' },
    { name: 'Cat6A Plenum Cable (1000ft)', labor_hours_per_unit: 5.5, system: 'STRUCTURED CABLING', category: 'Cable' },
    { name: 'Cat6A Riser Cable (1000ft)', labor_hours_per_unit: 5, system: 'STRUCTURED CABLING', category: 'Cable' },
    { name: 'Cat6A Shielded Plenum Cable (1000ft)', labor_hours_per_unit: 6, system: 'STRUCTURED CABLING', category: 'Cable' },
    { name: 'Cat6A Outdoor Direct Burial Cable (1000ft)', labor_hours_per_unit: 6, system: 'STRUCTURED CABLING', category: 'Cable' },
    { name: 'Cat6 Outdoor Gel-Filled Cable (1000ft)', labor_hours_per_unit: 5.5, system: 'STRUCTURED CABLING', category: 'Cable' },
    { name: '25-Pair Cat3 Cable (1000ft)', labor_hours_per_unit: 8, system: 'STRUCTURED CABLING', category: 'Cable' },
    { name: '50-Pair Cat3 Cable (1000ft)', labor_hours_per_unit: 10, system: 'STRUCTURED CABLING', category: 'Cable' },
    { name: '100-Pair Cat3 Cable (1000ft)', labor_hours_per_unit: 14, system: 'STRUCTURED CABLING', category: 'Cable' },
    // --- Fiber Cable ---
    { name: 'Single-Mode Fiber 6-Strand Indoor (1000ft)', labor_hours_per_unit: 8, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'Single-Mode Fiber 12-Strand Indoor (1000ft)', labor_hours_per_unit: 10, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'Single-Mode Fiber 24-Strand Indoor (1000ft)', labor_hours_per_unit: 14, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'Multi-Mode OM3 Fiber 6-Strand (1000ft)', labor_hours_per_unit: 8, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'Multi-Mode OM3 Fiber 12-Strand (1000ft)', labor_hours_per_unit: 10, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'Multi-Mode OM4 Fiber 12-Strand (1000ft)', labor_hours_per_unit: 10, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'Multi-Mode OM4 Fiber 24-Strand (1000ft)', labor_hours_per_unit: 14, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'Armored Fiber 12-Strand Outdoor (1000ft)', labor_hours_per_unit: 12, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'Armored Fiber 24-Strand Outdoor (1000ft)', labor_hours_per_unit: 16, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'Fiber Splice Enclosure', labor_hours_per_unit: 2, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'Fiber Splice Tray', labor_hours_per_unit: 0.5, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'Fiber Fusion Splice (per strand)', labor_hours_per_unit: 0.5, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'Fiber Mechanical Splice (per strand)', labor_hours_per_unit: 0.25, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'SC Fiber Connector', labor_hours_per_unit: 0.3, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'LC Fiber Connector', labor_hours_per_unit: 0.3, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'ST Fiber Connector', labor_hours_per_unit: 0.3, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'SC-LC Fiber Patch Cord 3ft', labor_hours_per_unit: 0.1, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'LC-LC Fiber Patch Cord 3ft', labor_hours_per_unit: 0.1, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'LC-LC Fiber Patch Cord 10ft', labor_hours_per_unit: 0.1, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'Fiber Optic Wall Mount Box 2-Port', labor_hours_per_unit: 0.5, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'Fiber Optic Wall Mount Box 4-Port', labor_hours_per_unit: 0.75, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'Fiber Patch Panel 12-Port Rack Mount', labor_hours_per_unit: 1.5, system: 'STRUCTURED CABLING', category: 'Fiber' },
    { name: 'Fiber Patch Panel 24-Port Rack Mount', labor_hours_per_unit: 2, system: 'STRUCTURED CABLING', category: 'Fiber' },
    // --- Connectors & Termination ---
    { name: 'Cat5e RJ45 Keystone Jack', labor_hours_per_unit: 0.15, system: 'STRUCTURED CABLING', category: 'Connectors' },
    { name: 'Cat6 RJ45 Keystone Jack', labor_hours_per_unit: 0.15, system: 'STRUCTURED CABLING', category: 'Connectors' },
    { name: 'Cat6A RJ45 Keystone Jack', labor_hours_per_unit: 0.2, system: 'STRUCTURED CABLING', category: 'Connectors' },
    { name: 'Cat6A Shielded RJ45 Keystone Jack', labor_hours_per_unit: 0.25, system: 'STRUCTURED CABLING', category: 'Connectors' },
    { name: 'RJ45 Plug (Crimp-On)', labor_hours_per_unit: 0.1, system: 'STRUCTURED CABLING', category: 'Connectors' },
    { name: 'Cat6 RJ45 Pass-Through Plug', labor_hours_per_unit: 0.1, system: 'STRUCTURED CABLING', category: 'Connectors' },
    { name: 'Cat6A Shielded RJ45 Plug', labor_hours_per_unit: 0.12, system: 'STRUCTURED CABLING', category: 'Connectors' },
    { name: '110 Punch-Down Block 50-Pair', labor_hours_per_unit: 1.5, system: 'STRUCTURED CABLING', category: 'Connectors' },
    { name: '110 Punch-Down Block 100-Pair', labor_hours_per_unit: 2.5, system: 'STRUCTURED CABLING', category: 'Connectors' },
    { name: '66 Punch-Down Block 50-Pair', labor_hours_per_unit: 1.5, system: 'STRUCTURED CABLING', category: 'Connectors' },
    { name: 'BIX Block 25-Pair', labor_hours_per_unit: 1, system: 'STRUCTURED CABLING', category: 'Connectors' },
    { name: 'Coax BNC Connector', labor_hours_per_unit: 0.15, system: 'STRUCTURED CABLING', category: 'Connectors' },
    { name: 'Coax F-Type Connector', labor_hours_per_unit: 0.1, system: 'STRUCTURED CABLING', category: 'Connectors' },
    { name: 'RG6 Coax Cable (1000ft)', labor_hours_per_unit: 5, system: 'STRUCTURED CABLING', category: 'Cable' },
    { name: 'RG59 Coax Cable (1000ft)', labor_hours_per_unit: 4.5, system: 'STRUCTURED CABLING', category: 'Cable' },
    // --- Patch Panels ---
    { name: '24-Port Cat6 Patch Panel 1U', labor_hours_per_unit: 1.5, system: 'STRUCTURED CABLING', category: 'Patch Panels' },
    { name: '48-Port Cat6 Patch Panel 2U', labor_hours_per_unit: 2.5, system: 'STRUCTURED CABLING', category: 'Patch Panels' },
    { name: '24-Port Cat6A Patch Panel 1U', labor_hours_per_unit: 1.5, system: 'STRUCTURED CABLING', category: 'Patch Panels' },
    { name: '48-Port Cat6A Patch Panel 2U', labor_hours_per_unit: 2.5, system: 'STRUCTURED CABLING', category: 'Patch Panels' },
    { name: '24-Port Cat6A Shielded Patch Panel', labor_hours_per_unit: 2, system: 'STRUCTURED CABLING', category: 'Patch Panels' },
    { name: '12-Port Patch Panel Wall Mount', labor_hours_per_unit: 1, system: 'STRUCTURED CABLING', category: 'Patch Panels' },
    { name: 'Blank Patch Panel 1U', labor_hours_per_unit: 0.5, system: 'STRUCTURED CABLING', category: 'Patch Panels' },
    { name: 'Blank Patch Panel 2U', labor_hours_per_unit: 0.5, system: 'STRUCTURED CABLING', category: 'Patch Panels' },
    { name: 'Angled Patch Panel 24-Port', labor_hours_per_unit: 1.5, system: 'STRUCTURED CABLING', category: 'Patch Panels' },
    // --- Faceplates & Wall Plates ---
    { name: 'Single-Gang Faceplate 1-Port', labor_hours_per_unit: 0.2, system: 'STRUCTURED CABLING', category: 'Faceplates' },
    { name: 'Single-Gang Faceplate 2-Port', labor_hours_per_unit: 0.2, system: 'STRUCTURED CABLING', category: 'Faceplates' },
    { name: 'Single-Gang Faceplate 4-Port', labor_hours_per_unit: 0.25, system: 'STRUCTURED CABLING', category: 'Faceplates' },
    { name: 'Single-Gang Faceplate 6-Port', labor_hours_per_unit: 0.3, system: 'STRUCTURED CABLING', category: 'Faceplates' },
    { name: 'Double-Gang Faceplate 6-Port', labor_hours_per_unit: 0.35, system: 'STRUCTURED CABLING', category: 'Faceplates' },
    { name: 'Double-Gang Faceplate 12-Port', labor_hours_per_unit: 0.4, system: 'STRUCTURED CABLING', category: 'Faceplates' },
    { name: 'Surface Mount Box Single-Gang', labor_hours_per_unit: 0.25, system: 'STRUCTURED CABLING', category: 'Faceplates' },
    { name: 'Surface Mount Box Double-Gang', labor_hours_per_unit: 0.3, system: 'STRUCTURED CABLING', category: 'Faceplates' },
    { name: 'Floor Box Assembly (raised floor)', labor_hours_per_unit: 1.5, system: 'STRUCTURED CABLING', category: 'Faceplates' },
    { name: 'Floor Box Assembly (concrete pour)', labor_hours_per_unit: 2, system: 'STRUCTURED CABLING', category: 'Faceplates' },
    { name: 'Furniture Feed Assembly', labor_hours_per_unit: 1, system: 'STRUCTURED CABLING', category: 'Faceplates' },
    { name: 'Blank Keystone Insert', labor_hours_per_unit: 0.05, system: 'STRUCTURED CABLING', category: 'Faceplates' },
    { name: 'Keystone Icon Insert', labor_hours_per_unit: 0.05, system: 'STRUCTURED CABLING', category: 'Faceplates' },
    // --- Patch Cords ---
    { name: 'Cat6 Patch Cord 3ft', labor_hours_per_unit: 0.05, system: 'STRUCTURED CABLING', category: 'Patch Cords' },
    { name: 'Cat6 Patch Cord 5ft', labor_hours_per_unit: 0.05, system: 'STRUCTURED CABLING', category: 'Patch Cords' },
    { name: 'Cat6 Patch Cord 7ft', labor_hours_per_unit: 0.05, system: 'STRUCTURED CABLING', category: 'Patch Cords' },
    { name: 'Cat6 Patch Cord 10ft', labor_hours_per_unit: 0.05, system: 'STRUCTURED CABLING', category: 'Patch Cords' },
    { name: 'Cat6 Patch Cord 14ft', labor_hours_per_unit: 0.05, system: 'STRUCTURED CABLING', category: 'Patch Cords' },
    { name: 'Cat6A Patch Cord 3ft', labor_hours_per_unit: 0.05, system: 'STRUCTURED CABLING', category: 'Patch Cords' },
    { name: 'Cat6A Patch Cord 7ft', labor_hours_per_unit: 0.05, system: 'STRUCTURED CABLING', category: 'Patch Cords' },
    { name: 'Cat6A Patch Cord 10ft', labor_hours_per_unit: 0.05, system: 'STRUCTURED CABLING', category: 'Patch Cords' },
    { name: 'Cat6A Shielded Patch Cord 7ft', labor_hours_per_unit: 0.05, system: 'STRUCTURED CABLING', category: 'Patch Cords' },
    // --- Support Hardware ---
    { name: 'J-Hooks 3/4" (box of 25)', labor_hours_per_unit: 0.5, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'J-Hooks 1-5/16" (box of 25)', labor_hours_per_unit: 0.5, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'J-Hooks 2" (box of 25)', labor_hours_per_unit: 0.5, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'J-Hooks 4" (box of 25)', labor_hours_per_unit: 0.6, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'Cable Ring 2" D-Ring (each)', labor_hours_per_unit: 0.15, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'Cable Ring 4" D-Ring (each)', labor_hours_per_unit: 0.15, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'Bridle Ring 2" (each)', labor_hours_per_unit: 0.1, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'Beam Clamp 1/2"-13', labor_hours_per_unit: 0.1, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'Threaded Rod 1/2"-13 x 6ft', labor_hours_per_unit: 0.25, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'Threaded Rod 3/8"-16 x 6ft', labor_hours_per_unit: 0.2, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'Drop Wire / Trapeze Kit', labor_hours_per_unit: 0.5, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'Cable Tray 12" Wire Basket (10ft)', labor_hours_per_unit: 0.75, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'Cable Tray 18" Wire Basket (10ft)', labor_hours_per_unit: 0.85, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'Cable Tray 24" Wire Basket (10ft)', labor_hours_per_unit: 1, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'Cable Tray 6" Solid Bottom (10ft)', labor_hours_per_unit: 0.85, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'Cable Tray Splice Plate', labor_hours_per_unit: 0.15, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'Cable Tray Wall Bracket', labor_hours_per_unit: 0.25, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'Cable Tray Center Hung Support', labor_hours_per_unit: 0.35, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'Cable Tray Elbow 90°', labor_hours_per_unit: 0.4, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'Cable Tray Tee Fitting', labor_hours_per_unit: 0.5, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'Cable Tray Drop-Out', labor_hours_per_unit: 0.35, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'Ladder Rack 12" (10ft)', labor_hours_per_unit: 1, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'Ladder Rack 18" (10ft)', labor_hours_per_unit: 1.2, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'Ladder Rack 24" (10ft)', labor_hours_per_unit: 1.5, system: 'STRUCTURED CABLING', category: 'Support' },
    { name: 'Ladder Rack Bracket/Support', labor_hours_per_unit: 0.3, system: 'STRUCTURED CABLING', category: 'Support' },
    // --- Networking Equipment ---
    { name: 'Wireless Access Point (WAP)', labor_hours_per_unit: 0.75, system: 'STRUCTURED CABLING', category: 'Networking' },
    { name: 'WAP Ceiling Mount Bracket', labor_hours_per_unit: 0.25, system: 'STRUCTURED CABLING', category: 'Networking' },
    { name: 'WAP Wall Mount Bracket', labor_hours_per_unit: 0.25, system: 'STRUCTURED CABLING', category: 'Networking' },
    { name: '24-Port PoE+ Network Switch', labor_hours_per_unit: 1.5, system: 'STRUCTURED CABLING', category: 'Networking' },
    { name: '48-Port PoE+ Network Switch', labor_hours_per_unit: 2, system: 'STRUCTURED CABLING', category: 'Networking' },
    { name: '8-Port PoE+ Network Switch', labor_hours_per_unit: 0.75, system: 'STRUCTURED CABLING', category: 'Networking' },
    { name: 'PoE Injector Single-Port', labor_hours_per_unit: 0.15, system: 'STRUCTURED CABLING', category: 'Networking' },
    { name: 'PoE Midspan 12-Port', labor_hours_per_unit: 0.75, system: 'STRUCTURED CABLING', category: 'Networking' },
    { name: 'Network UPS 1500VA Rack Mount', labor_hours_per_unit: 1.5, system: 'STRUCTURED CABLING', category: 'Networking' },
    { name: 'Network UPS 3000VA Rack Mount', labor_hours_per_unit: 2, system: 'STRUCTURED CABLING', category: 'Networking' },
    { name: 'PDU (Power Distribution Unit) Basic', labor_hours_per_unit: 0.5, system: 'STRUCTURED CABLING', category: 'Networking' },
    { name: 'PDU Managed Rack Mount', labor_hours_per_unit: 1, system: 'STRUCTURED CABLING', category: 'Networking' },
    // --- Cable Management ---
    { name: 'Horizontal Cable Manager 1U', labor_hours_per_unit: 0.25, system: 'STRUCTURED CABLING', category: 'Management' },
    { name: 'Horizontal Cable Manager 2U', labor_hours_per_unit: 0.3, system: 'STRUCTURED CABLING', category: 'Management' },
    { name: 'Vertical Cable Manager 6ft', labor_hours_per_unit: 0.5, system: 'STRUCTURED CABLING', category: 'Management' },
    { name: 'Velcro Roll 75ft', labor_hours_per_unit: 0.1, system: 'STRUCTURED CABLING', category: 'Management' },
    { name: 'Velcro Straps (bundle of 100)', labor_hours_per_unit: 0.5, system: 'STRUCTURED CABLING', category: 'Management' },
    { name: 'Cable Ties 8" (bag of 100)', labor_hours_per_unit: 0.25, system: 'STRUCTURED CABLING', category: 'Management' },
    { name: 'Cable Labels Self-Laminating (roll of 100)', labor_hours_per_unit: 1.5, system: 'STRUCTURED CABLING', category: 'Management' },
    { name: 'Cable Labels Wrap-Around (roll of 100)', labor_hours_per_unit: 1, system: 'STRUCTURED CABLING', category: 'Management' },
    { name: 'Patch Panel Label Strip', labor_hours_per_unit: 0.25, system: 'STRUCTURED CABLING', category: 'Management' },
    { name: 'Cable Boot RJ45 (bag of 50)', labor_hours_per_unit: 0.25, system: 'STRUCTURED CABLING', category: 'Management' },
    { name: 'Lacing Bar / Cable Lacing Strip', labor_hours_per_unit: 0.15, system: 'STRUCTURED CABLING', category: 'Management' },
    // --- Testing & Certification ---
    { name: 'Data Drop Testing & Certification (per drop)', labor_hours_per_unit: 0.15, system: 'STRUCTURED CABLING', category: 'Testing' },
    { name: 'Fiber Testing OTDR (per strand)', labor_hours_per_unit: 0.25, system: 'STRUCTURED CABLING', category: 'Testing' },
    { name: 'Fiber Power Meter Test (per strand)', labor_hours_per_unit: 0.1, system: 'STRUCTURED CABLING', category: 'Testing' },
    { name: 'Coax Cable Test & Cert (per drop)', labor_hours_per_unit: 0.1, system: 'STRUCTURED CABLING', category: 'Testing' },
    { name: 'Complete Drop (pull+term+test)', labor_hours_per_unit: 0.75, system: 'STRUCTURED CABLING', category: 'Testing' },
    // --- Boxes & Enclosures ---
    { name: 'Single-Gang Low-Voltage Bracket (Old Work)', labor_hours_per_unit: 0.15, system: 'STRUCTURED CABLING', category: 'Boxes' },
    { name: 'Single-Gang Low-Voltage Bracket (New Work)', labor_hours_per_unit: 0.1, system: 'STRUCTURED CABLING', category: 'Boxes' },
    { name: 'Double-Gang Low-Voltage Bracket', labor_hours_per_unit: 0.15, system: 'STRUCTURED CABLING', category: 'Boxes' },
    { name: '4x4 Junction Box', labor_hours_per_unit: 0.25, system: 'STRUCTURED CABLING', category: 'Boxes' },
    { name: '6x6 Junction Box', labor_hours_per_unit: 0.3, system: 'STRUCTURED CABLING', category: 'Boxes' },
    { name: '8x8 Junction Box', labor_hours_per_unit: 0.35, system: 'STRUCTURED CABLING', category: 'Boxes' },
    { name: '12x12 Pull Box', labor_hours_per_unit: 0.75, system: 'STRUCTURED CABLING', category: 'Boxes' },
    { name: '18x18 Pull Box', labor_hours_per_unit: 1, system: 'STRUCTURED CABLING', category: 'Boxes' },
    { name: '24x24 Pull Box', labor_hours_per_unit: 1.5, system: 'STRUCTURED CABLING', category: 'Boxes' },
    { name: 'NEMA 1 Enclosure 12x12x6', labor_hours_per_unit: 1, system: 'STRUCTURED CABLING', category: 'Boxes' },
    { name: 'NEMA 4 Enclosure 16x16x8', labor_hours_per_unit: 1.5, system: 'STRUCTURED CABLING', category: 'Boxes' },
    // --- Grounding & Bonding ---
    { name: 'Telecommunications Grounding Bar (TGB)', labor_hours_per_unit: 1.5, system: 'STRUCTURED CABLING', category: 'Grounding' },
    { name: 'Telecommunications Bonding Backbone (TBB) #6 AWG (per 100ft)', labor_hours_per_unit: 2, system: 'STRUCTURED CABLING', category: 'Grounding' },
    { name: 'Ground Lug 2-Hole', labor_hours_per_unit: 0.15, system: 'STRUCTURED CABLING', category: 'Grounding' },
    { name: 'Rack Grounding Kit', labor_hours_per_unit: 0.5, system: 'STRUCTURED CABLING', category: 'Grounding' },
    { name: 'Bonding Conductor #6 THHN Green (per 100ft)', labor_hours_per_unit: 1, system: 'STRUCTURED CABLING', category: 'Grounding' },
    // --- Miscellaneous ---
    { name: 'Innerduct 1" (100ft)', labor_hours_per_unit: 2, system: 'STRUCTURED CABLING', category: 'Misc' },
    { name: 'Innerduct 2" (100ft)', labor_hours_per_unit: 2.5, system: 'STRUCTURED CABLING', category: 'Misc' },
    { name: 'Pull String / Mule Tape (per 1000ft)', labor_hours_per_unit: 1, system: 'STRUCTURED CABLING', category: 'Misc' },
    { name: 'Cable Lubricant (gallon)', labor_hours_per_unit: 0.1, system: 'STRUCTURED CABLING', category: 'Misc' },
    { name: 'Demarc Extension', labor_hours_per_unit: 4, system: 'STRUCTURED CABLING', category: 'Misc' },
    { name: 'MDF/IDF Backboard 4x8 Plywood', labor_hours_per_unit: 2, system: 'STRUCTURED CABLING', category: 'Misc' },
    { name: 'Panduit Raceway (per 6ft)', labor_hours_per_unit: 0.75, system: 'STRUCTURED CABLING', category: 'Misc' },
    { name: 'Wiremold Raceway (per 5ft)', labor_hours_per_unit: 0.6, system: 'STRUCTURED CABLING', category: 'Misc' },
    { name: 'Multi-Port Surface Box 4-Port', labor_hours_per_unit: 0.3, system: 'STRUCTURED CABLING', category: 'Misc' },
    { name: 'Modular Furniture Adapter', labor_hours_per_unit: 0.4, system: 'STRUCTURED CABLING', category: 'Misc' },
    { name: 'Cable Drop (complete installed drop)', labor_hours_per_unit: 0.75, system: 'STRUCTURED CABLING', category: 'Misc' },
];

// ============================================================
// 2. CCTV / SECURITY CAMERAS
// ============================================================
const CCTV: MaterialItem[] = [
    // --- Cameras ---
    { name: 'IP Dome Camera Indoor', labor_hours_per_unit: 1, system: 'CCTV', category: 'Cameras' },
    { name: 'IP Dome Camera Outdoor Vandal-Proof', labor_hours_per_unit: 1.25, system: 'CCTV', category: 'Cameras' },
    { name: 'IP Bullet Camera Indoor', labor_hours_per_unit: 1, system: 'CCTV', category: 'Cameras' },
    { name: 'IP Bullet Camera Outdoor', labor_hours_per_unit: 1.25, system: 'CCTV', category: 'Cameras' },
    { name: 'IP Turret Camera Indoor', labor_hours_per_unit: 1, system: 'CCTV', category: 'Cameras' },
    { name: 'IP Turret Camera Outdoor', labor_hours_per_unit: 1.25, system: 'CCTV', category: 'Cameras' },
    { name: 'IP PTZ Camera Indoor', labor_hours_per_unit: 2, system: 'CCTV', category: 'Cameras' },
    { name: 'IP PTZ Camera Outdoor', labor_hours_per_unit: 2.5, system: 'CCTV', category: 'Cameras' },
    { name: 'IP Fisheye/Panoramic Camera', labor_hours_per_unit: 1.5, system: 'CCTV', category: 'Cameras' },
    { name: 'IP Multi-Sensor Camera (180°)', labor_hours_per_unit: 2, system: 'CCTV', category: 'Cameras' },
    { name: 'IP Multi-Sensor Camera (360°)', labor_hours_per_unit: 2, system: 'CCTV', category: 'Cameras' },
    { name: 'License Plate Recognition (LPR) Camera', labor_hours_per_unit: 2, system: 'CCTV', category: 'Cameras' },
    { name: 'Thermal Camera', labor_hours_per_unit: 2, system: 'CCTV', category: 'Cameras' },
    { name: 'Body-Worn Camera', labor_hours_per_unit: 0.25, system: 'CCTV', category: 'Cameras' },
    { name: 'Covert/Pinhole Camera', labor_hours_per_unit: 1.5, system: 'CCTV', category: 'Cameras' },
    { name: 'Explosion-Proof Camera Housing', labor_hours_per_unit: 3, system: 'CCTV', category: 'Cameras' },
    { name: 'Corner Mount Camera', labor_hours_per_unit: 1.25, system: 'CCTV', category: 'Cameras' },
    { name: 'Elevator Camera', labor_hours_per_unit: 1.5, system: 'CCTV', category: 'Cameras' },
    { name: 'IP Doorbell Camera', labor_hours_per_unit: 1, system: 'CCTV', category: 'Cameras' },
    { name: '4K IP Dome Camera', labor_hours_per_unit: 1, system: 'CCTV', category: 'Cameras' },
    { name: '4K IP Bullet Camera', labor_hours_per_unit: 1, system: 'CCTV', category: 'Cameras' },
    { name: '8MP Multi-Imager Camera', labor_hours_per_unit: 2.5, system: 'CCTV', category: 'Cameras' },
    // --- Recording & Server ---
    { name: 'NVR 8-Channel', labor_hours_per_unit: 2, system: 'CCTV', category: 'Recording' },
    { name: 'NVR 16-Channel', labor_hours_per_unit: 2.5, system: 'CCTV', category: 'Recording' },
    { name: 'NVR 32-Channel', labor_hours_per_unit: 3, system: 'CCTV', category: 'Recording' },
    { name: 'NVR 64-Channel', labor_hours_per_unit: 4, system: 'CCTV', category: 'Recording' },
    { name: 'NVR 128-Channel Enterprise', labor_hours_per_unit: 6, system: 'CCTV', category: 'Recording' },
    { name: 'VMS Server (Video Management)', labor_hours_per_unit: 8, system: 'CCTV', category: 'Recording' },
    { name: 'VMS Software License (per camera)', labor_hours_per_unit: 0.25, system: 'CCTV', category: 'Recording' },
    { name: 'Hard Drive 4TB Surveillance Grade', labor_hours_per_unit: 0.25, system: 'CCTV', category: 'Recording' },
    { name: 'Hard Drive 8TB Surveillance Grade', labor_hours_per_unit: 0.25, system: 'CCTV', category: 'Recording' },
    { name: 'Hard Drive 10TB Surveillance Grade', labor_hours_per_unit: 0.25, system: 'CCTV', category: 'Recording' },
    { name: 'RAID Storage Array', labor_hours_per_unit: 4, system: 'CCTV', category: 'Recording' },
    // --- Monitors & Display ---
    { name: 'Video Monitor 22"', labor_hours_per_unit: 0.5, system: 'CCTV', category: 'Display' },
    { name: 'Video Monitor 27"', labor_hours_per_unit: 0.5, system: 'CCTV', category: 'Display' },
    { name: 'Video Monitor 32"', labor_hours_per_unit: 0.75, system: 'CCTV', category: 'Display' },
    { name: 'Video Monitor 43"', labor_hours_per_unit: 1, system: 'CCTV', category: 'Display' },
    { name: 'Video Monitor 55"', labor_hours_per_unit: 1.5, system: 'CCTV', category: 'Display' },
    { name: 'Video Wall Display 55" Bezel-less', labor_hours_per_unit: 2, system: 'CCTV', category: 'Display' },
    { name: 'Video Wall Controller/Decoder', labor_hours_per_unit: 2, system: 'CCTV', category: 'Display' },
    { name: 'Monitor Wall Mount', labor_hours_per_unit: 0.5, system: 'CCTV', category: 'Display' },
    { name: 'Monitor Desk Stand', labor_hours_per_unit: 0.25, system: 'CCTV', category: 'Display' },
    { name: 'KVM Switch for Monitors', labor_hours_per_unit: 0.5, system: 'CCTV', category: 'Display' },
    // --- Camera Mounts & Housings ---
    { name: 'Camera Wall Mount Bracket', labor_hours_per_unit: 0.25, system: 'CCTV', category: 'Mounts' },
    { name: 'Camera Ceiling Mount Bracket', labor_hours_per_unit: 0.3, system: 'CCTV', category: 'Mounts' },
    { name: 'Camera Pendant Mount', labor_hours_per_unit: 0.4, system: 'CCTV', category: 'Mounts' },
    { name: 'Camera Pole Mount Adapter', labor_hours_per_unit: 0.5, system: 'CCTV', category: 'Mounts' },
    { name: 'Camera Corner Mount Bracket', labor_hours_per_unit: 0.35, system: 'CCTV', category: 'Mounts' },
    { name: 'Camera Parapet Mount', labor_hours_per_unit: 0.5, system: 'CCTV', category: 'Mounts' },
    { name: 'Camera Junction Box / Back Box', labor_hours_per_unit: 0.25, system: 'CCTV', category: 'Mounts' },
    { name: 'Camera Gooseneck Mount', labor_hours_per_unit: 0.5, system: 'CCTV', category: 'Mounts' },
    { name: 'Camera Extension Arm 12"', labor_hours_per_unit: 0.3, system: 'CCTV', category: 'Mounts' },
    { name: 'Camera Extension Arm 24"', labor_hours_per_unit: 0.35, system: 'CCTV', category: 'Mounts' },
    { name: 'Camera Pole / Mast 12ft', labor_hours_per_unit: 4, system: 'CCTV', category: 'Mounts' },
    { name: 'Camera Pole / Mast 20ft', labor_hours_per_unit: 6, system: 'CCTV', category: 'Mounts' },
    { name: 'Camera Pole / Mast 30ft', labor_hours_per_unit: 8, system: 'CCTV', category: 'Mounts' },
    { name: 'Camera Weatherproof Housing', labor_hours_per_unit: 0.5, system: 'CCTV', category: 'Mounts' },
    { name: 'Camera Housing Heater/Blower', labor_hours_per_unit: 0.5, system: 'CCTV', category: 'Mounts' },
    { name: 'Camera Sunshield', labor_hours_per_unit: 0.15, system: 'CCTV', category: 'Mounts' },
    // --- Networking & Power ---
    { name: '8-Port PoE Switch for CCTV', labor_hours_per_unit: 0.75, system: 'CCTV', category: 'Networking' },
    { name: '16-Port PoE Switch for CCTV', labor_hours_per_unit: 1, system: 'CCTV', category: 'Networking' },
    { name: '24-Port PoE+ Switch for CCTV', labor_hours_per_unit: 1.5, system: 'CCTV', category: 'Networking' },
    { name: 'PoE Extender / Repeater', labor_hours_per_unit: 0.25, system: 'CCTV', category: 'Networking' },
    { name: 'PoE Injector 30W', labor_hours_per_unit: 0.15, system: 'CCTV', category: 'Networking' },
    { name: 'PoE Injector 60W (PoE++)', labor_hours_per_unit: 0.15, system: 'CCTV', category: 'Networking' },
    { name: 'Media Converter Fiber-to-Copper', labor_hours_per_unit: 0.5, system: 'CCTV', category: 'Networking' },
    { name: 'Ethernet Over Coax Adapter', labor_hours_per_unit: 0.35, system: 'CCTV', category: 'Networking' },
    { name: 'Wireless Bridge (Point-to-Point)', labor_hours_per_unit: 2, system: 'CCTV', category: 'Networking' },
    { name: 'Wireless Mesh Node', labor_hours_per_unit: 1.5, system: 'CCTV', category: 'Networking' },
    // --- CCTV Cable ---
    { name: 'Cat6 Outdoor Shielded for CCTV (1000ft)', labor_hours_per_unit: 5.5, system: 'CCTV', category: 'Cable' },
    { name: 'Cat6 Plenum for IP Cameras (1000ft)', labor_hours_per_unit: 5, system: 'CCTV', category: 'Cable' },
    { name: 'Siamese RG59 + 18/2 (1000ft)', labor_hours_per_unit: 5, system: 'CCTV', category: 'Cable' },
    { name: 'Single-Mode Fiber for Remote Cameras (1000ft)', labor_hours_per_unit: 8, system: 'CCTV', category: 'Cable' },
    // --- CCTV Accessories ---
    { name: 'IR Illuminator / LED Flood', labor_hours_per_unit: 0.75, system: 'CCTV', category: 'Accessories' },
    { name: 'White Light Illuminator', labor_hours_per_unit: 0.75, system: 'CCTV', category: 'Accessories' },
    { name: 'Camera Lens (Varifocal)', labor_hours_per_unit: 0.25, system: 'CCTV', category: 'Accessories' },
    { name: 'Camera SD Card 64GB', labor_hours_per_unit: 0.1, system: 'CCTV', category: 'Accessories' },
    { name: 'Camera SD Card 256GB', labor_hours_per_unit: 0.1, system: 'CCTV', category: 'Accessories' },
    { name: 'Surge Protector PoE', labor_hours_per_unit: 0.15, system: 'CCTV', category: 'Accessories' },
    { name: 'Ethernet Surge Protector', labor_hours_per_unit: 0.15, system: 'CCTV', category: 'Accessories' },
    { name: 'Audio Microphone for Camera', labor_hours_per_unit: 0.25, system: 'CCTV', category: 'Accessories' },
    { name: 'Speaker for Two-Way Audio Camera', labor_hours_per_unit: 0.25, system: 'CCTV', category: 'Accessories' },
    { name: 'I/O Module for Camera', labor_hours_per_unit: 0.25, system: 'CCTV', category: 'Accessories' },
    { name: '12VDC Power Supply for Camera', labor_hours_per_unit: 0.25, system: 'CCTV', category: 'Accessories' },
    { name: '24VAC Power Supply for Camera', labor_hours_per_unit: 0.25, system: 'CCTV', category: 'Accessories' },
    { name: 'Multi-Camera Power Supply 8-Port', labor_hours_per_unit: 0.75, system: 'CCTV', category: 'Accessories' },
    { name: 'Multi-Camera Power Supply 16-Port', labor_hours_per_unit: 1, system: 'CCTV', category: 'Accessories' },
    { name: 'Video Balun Pair', labor_hours_per_unit: 0.2, system: 'CCTV', category: 'Accessories' },
    { name: 'Network Video Encoder 1-Channel', labor_hours_per_unit: 0.5, system: 'CCTV', category: 'Accessories' },
    { name: 'Network Video Encoder 4-Channel', labor_hours_per_unit: 1, system: 'CCTV', category: 'Accessories' },
    { name: 'Video Analytics License (per camera)', labor_hours_per_unit: 0.5, system: 'CCTV', category: 'Accessories' },
    { name: 'CCTV Warning Signage', labor_hours_per_unit: 0.1, system: 'CCTV', category: 'Accessories' },
    { name: 'Camera Tamper Switch', labor_hours_per_unit: 0.15, system: 'CCTV', category: 'Accessories' },
];

// ============================================================
// 3. ACCESS CONTROL
// ============================================================
const ACCESS_CONTROL: MaterialItem[] = [
    // --- Readers ---
    { name: 'Proximity Card Reader', labor_hours_per_unit: 1, system: 'ACCESS CONTROL', category: 'Readers' },
    { name: 'Smart Card Reader (iCLASS)', labor_hours_per_unit: 1, system: 'ACCESS CONTROL', category: 'Readers' },
    { name: 'Multi-Technology Card Reader (Prox+Smart)', labor_hours_per_unit: 1, system: 'ACCESS CONTROL', category: 'Readers' },
    { name: 'Mobile Credential Reader (Bluetooth/NFC)', labor_hours_per_unit: 1, system: 'ACCESS CONTROL', category: 'Readers' },
    { name: 'Biometric Fingerprint Reader', labor_hours_per_unit: 1.5, system: 'ACCESS CONTROL', category: 'Readers' },
    { name: 'Biometric Iris Scanner', labor_hours_per_unit: 2, system: 'ACCESS CONTROL', category: 'Readers' },
    { name: 'Biometric Facial Recognition Reader', labor_hours_per_unit: 2, system: 'ACCESS CONTROL', category: 'Readers' },
    { name: 'Keypad Reader (PIN)', labor_hours_per_unit: 1, system: 'ACCESS CONTROL', category: 'Readers' },
    { name: 'Keypad + Card Reader Combo', labor_hours_per_unit: 1.25, system: 'ACCESS CONTROL', category: 'Readers' },
    { name: 'Long-Range Reader (Parking)', labor_hours_per_unit: 2, system: 'ACCESS CONTROL', category: 'Readers' },
    { name: 'Mullion Mount Reader', labor_hours_per_unit: 1, system: 'ACCESS CONTROL', category: 'Readers' },
    { name: 'Outdoor/Weatherproof Reader', labor_hours_per_unit: 1.25, system: 'ACCESS CONTROL', category: 'Readers' },
    { name: 'Elevator Reader', labor_hours_per_unit: 1.5, system: 'ACCESS CONTROL', category: 'Readers' },
    { name: 'Turnstile Reader', labor_hours_per_unit: 1.5, system: 'ACCESS CONTROL', category: 'Readers' },
    { name: 'Reader Mounting Plate', labor_hours_per_unit: 0.15, system: 'ACCESS CONTROL', category: 'Readers' },
    { name: 'Reader Gang Box', labor_hours_per_unit: 0.2, system: 'ACCESS CONTROL', category: 'Readers' },
    // --- Controllers & Panels ---
    { name: 'Access Control Panel 2-Door', labor_hours_per_unit: 3, system: 'ACCESS CONTROL', category: 'Controllers' },
    { name: 'Access Control Panel 4-Door', labor_hours_per_unit: 4, system: 'ACCESS CONTROL', category: 'Controllers' },
    { name: 'Access Control Panel 8-Door', labor_hours_per_unit: 6, system: 'ACCESS CONTROL', category: 'Controllers' },
    { name: 'Access Control Panel Single-Door (IP)', labor_hours_per_unit: 2, system: 'ACCESS CONTROL', category: 'Controllers' },
    { name: 'Elevator Controller Module', labor_hours_per_unit: 4, system: 'ACCESS CONTROL', category: 'Controllers' },
    { name: 'Input Monitor Module (8-input)', labor_hours_per_unit: 1.5, system: 'ACCESS CONTROL', category: 'Controllers' },
    { name: 'Output Relay Module (8-output)', labor_hours_per_unit: 1.5, system: 'ACCESS CONTROL', category: 'Controllers' },
    { name: 'Door Controller Board', labor_hours_per_unit: 1.5, system: 'ACCESS CONTROL', category: 'Controllers' },
    { name: 'AC Server / Head-End PC', labor_hours_per_unit: 4, system: 'ACCESS CONTROL', category: 'Controllers' },
    { name: 'AC Software License (per door)', labor_hours_per_unit: 0.25, system: 'ACCESS CONTROL', category: 'Controllers' },
    { name: 'AC Workstation License', labor_hours_per_unit: 0.5, system: 'ACCESS CONTROL', category: 'Controllers' },
    // --- Locking Hardware ---
    { name: 'Electric Strike (fail-secure)', labor_hours_per_unit: 1.5, system: 'ACCESS CONTROL', category: 'Locks' },
    { name: 'Electric Strike (fail-safe)', labor_hours_per_unit: 1.5, system: 'ACCESS CONTROL', category: 'Locks' },
    { name: 'Magnetic Lock 600lb', labor_hours_per_unit: 1.5, system: 'ACCESS CONTROL', category: 'Locks' },
    { name: 'Magnetic Lock 1200lb', labor_hours_per_unit: 1.75, system: 'ACCESS CONTROL', category: 'Locks' },
    { name: 'Magnetic Lock 1500lb', labor_hours_per_unit: 2, system: 'ACCESS CONTROL', category: 'Locks' },
    { name: 'Mag Lock Mounting Bracket (L/Z)', labor_hours_per_unit: 0.5, system: 'ACCESS CONTROL', category: 'Locks' },
    { name: 'Electric Latch Retraction (ELR) Kit', labor_hours_per_unit: 3, system: 'ACCESS CONTROL', category: 'Locks' },
    { name: 'Electrified Mortise Lock', labor_hours_per_unit: 3, system: 'ACCESS CONTROL', category: 'Locks' },
    { name: 'Electrified Panic Bar / Exit Device', labor_hours_per_unit: 3, system: 'ACCESS CONTROL', category: 'Locks' },
    { name: 'Electric Bolt Lock', labor_hours_per_unit: 2, system: 'ACCESS CONTROL', category: 'Locks' },
    { name: 'Electrified Deadbolt', labor_hours_per_unit: 2, system: 'ACCESS CONTROL', category: 'Locks' },
    { name: 'Wireless Lock (WiFi/BLE)', labor_hours_per_unit: 1.5, system: 'ACCESS CONTROL', category: 'Locks' },
    { name: 'Gate Lock / Gate Latch Electric', labor_hours_per_unit: 2, system: 'ACCESS CONTROL', category: 'Locks' },
    { name: 'Cabinet Lock Electric', labor_hours_per_unit: 1, system: 'ACCESS CONTROL', category: 'Locks' },
    // --- Door Hardware ---
    { name: 'Door Position Switch (Contact)', labor_hours_per_unit: 0.5, system: 'ACCESS CONTROL', category: 'Door Hardware' },
    { name: 'Door Position Switch Concealed', labor_hours_per_unit: 0.75, system: 'ACCESS CONTROL', category: 'Door Hardware' },
    { name: 'REX (Request to Exit) Motion Sensor', labor_hours_per_unit: 0.5, system: 'ACCESS CONTROL', category: 'Door Hardware' },
    { name: 'REX Push Button', labor_hours_per_unit: 0.4, system: 'ACCESS CONTROL', category: 'Door Hardware' },
    { name: 'REX Touch Bar', labor_hours_per_unit: 0.5, system: 'ACCESS CONTROL', category: 'Door Hardware' },
    { name: 'Door Closer (Standard)', labor_hours_per_unit: 1.5, system: 'ACCESS CONTROL', category: 'Door Hardware' },
    { name: 'ADA Door Operator (Automatic)', labor_hours_per_unit: 6, system: 'ACCESS CONTROL', category: 'Door Hardware' },
    { name: 'ADA Push Plate', labor_hours_per_unit: 0.5, system: 'ACCESS CONTROL', category: 'Door Hardware' },
    { name: 'Door Holder Electromagnetic', labor_hours_per_unit: 0.75, system: 'ACCESS CONTROL', category: 'Door Hardware' },
    { name: 'Exit Alarm / Door Prop Alarm', labor_hours_per_unit: 0.75, system: 'ACCESS CONTROL', category: 'Door Hardware' },
    { name: 'Glass Break Sensor (for AC door)', labor_hours_per_unit: 0.3, system: 'ACCESS CONTROL', category: 'Door Hardware' },
    { name: 'Door Hinge Transfer', labor_hours_per_unit: 1, system: 'ACCESS CONTROL', category: 'Door Hardware' },
    { name: 'Power Transfer Hinge', labor_hours_per_unit: 1.5, system: 'ACCESS CONTROL', category: 'Door Hardware' },
    { name: 'Electric Power Transfer (EPT)', labor_hours_per_unit: 1, system: 'ACCESS CONTROL', category: 'Door Hardware' },
    { name: 'Door Loop Cord', labor_hours_per_unit: 0.25, system: 'ACCESS CONTROL', category: 'Door Hardware' },
    { name: 'Header / Filler Plate', labor_hours_per_unit: 0.25, system: 'ACCESS CONTROL', category: 'Door Hardware' },
    // --- Credentials ---
    { name: 'Proximity Card (per 100)', labor_hours_per_unit: 1, system: 'ACCESS CONTROL', category: 'Credentials' },
    { name: 'Smart Card iCLASS (per 100)', labor_hours_per_unit: 1, system: 'ACCESS CONTROL', category: 'Credentials' },
    { name: 'Key Fob (per 25)', labor_hours_per_unit: 0.5, system: 'ACCESS CONTROL', category: 'Credentials' },
    { name: 'Proximity Card Sticker/Tag', labor_hours_per_unit: 0.05, system: 'ACCESS CONTROL', category: 'Credentials' },
    { name: 'Mobile Credential License (per user)', labor_hours_per_unit: 0.1, system: 'ACCESS CONTROL', category: 'Credentials' },
    // --- Access Control Cable ---
    { name: '18/4 Shielded Cable (1000ft) - Reader', labor_hours_per_unit: 5, system: 'ACCESS CONTROL', category: 'Cable' },
    { name: '22/6 Shielded Cable (1000ft) - REX/Contact', labor_hours_per_unit: 4.5, system: 'ACCESS CONTROL', category: 'Cable' },
    { name: '18/2 Cable (1000ft) - Lock Power', labor_hours_per_unit: 4, system: 'ACCESS CONTROL', category: 'Cable' },
    { name: '22/4 Shielded Cable (1000ft)', labor_hours_per_unit: 4, system: 'ACCESS CONTROL', category: 'Cable' },
    { name: '16/2 Cable (1000ft) - Mag Lock', labor_hours_per_unit: 4, system: 'ACCESS CONTROL', category: 'Cable' },
    { name: 'Composite Access Cable (22/6+18/4+22/2)', labor_hours_per_unit: 6, system: 'ACCESS CONTROL', category: 'Cable' },
    { name: 'Cat6 Cable for IP Readers (1000ft)', labor_hours_per_unit: 5, system: 'ACCESS CONTROL', category: 'Cable' },
    // --- Power Supplies ---
    { name: 'AC Power Supply 12VDC 2A', labor_hours_per_unit: 0.5, system: 'ACCESS CONTROL', category: 'Power' },
    { name: 'AC Power Supply 12VDC 4A', labor_hours_per_unit: 0.75, system: 'ACCESS CONTROL', category: 'Power' },
    { name: 'AC Power Supply 12VDC 10A', labor_hours_per_unit: 1, system: 'ACCESS CONTROL', category: 'Power' },
    { name: 'AC Power Supply 24VDC 4A', labor_hours_per_unit: 0.75, system: 'ACCESS CONTROL', category: 'Power' },
    { name: 'AC Power Supply 24VDC 10A', labor_hours_per_unit: 1, system: 'ACCESS CONTROL', category: 'Power' },
    { name: 'AC Power Supply w/ Battery Backup', labor_hours_per_unit: 1.5, system: 'ACCESS CONTROL', category: 'Power' },
    { name: 'Lock Power Supply (multi-lock)', labor_hours_per_unit: 1, system: 'ACCESS CONTROL', category: 'Power' },
    { name: 'Backup Battery 12V 7Ah', labor_hours_per_unit: 0.15, system: 'ACCESS CONTROL', category: 'Power' },
    { name: 'Backup Battery 12V 12Ah', labor_hours_per_unit: 0.15, system: 'ACCESS CONTROL', category: 'Power' },
    { name: 'Enclosure for Power Supply/Controller', labor_hours_per_unit: 0.5, system: 'ACCESS CONTROL', category: 'Power' },
    // --- Barriers & Turnstiles ---
    { name: 'Turnstile Full-Height', labor_hours_per_unit: 16, system: 'ACCESS CONTROL', category: 'Barriers' },
    { name: 'Turnstile Waist-Height', labor_hours_per_unit: 8, system: 'ACCESS CONTROL', category: 'Barriers' },
    { name: 'Optical Turnstile / Speed Gate', labor_hours_per_unit: 12, system: 'ACCESS CONTROL', category: 'Barriers' },
    { name: 'Vehicle Barrier Arm Gate', labor_hours_per_unit: 8, system: 'ACCESS CONTROL', category: 'Barriers' },
    { name: 'Bollard Retractable', labor_hours_per_unit: 8, system: 'ACCESS CONTROL', category: 'Barriers' },
    { name: 'Mantrap / Interlock Door System', labor_hours_per_unit: 16, system: 'ACCESS CONTROL', category: 'Barriers' },
    { name: 'Sliding Gate Operator', labor_hours_per_unit: 8, system: 'ACCESS CONTROL', category: 'Barriers' },
    { name: 'Swing Gate Operator', labor_hours_per_unit: 8, system: 'ACCESS CONTROL', category: 'Barriers' },
    // --- Intercom ---
    { name: 'Door Intercom Station (Audio)', labor_hours_per_unit: 1.5, system: 'ACCESS CONTROL', category: 'Intercom' },
    { name: 'Door Intercom Station (Video)', labor_hours_per_unit: 2, system: 'ACCESS CONTROL', category: 'Intercom' },
    { name: 'Interior Intercom Master Station', labor_hours_per_unit: 1, system: 'ACCESS CONTROL', category: 'Intercom' },
    { name: 'Telephone Entry System', labor_hours_per_unit: 4, system: 'ACCESS CONTROL', category: 'Intercom' },
    { name: 'Intercom Sub-Station', labor_hours_per_unit: 0.75, system: 'ACCESS CONTROL', category: 'Intercom' },
    { name: 'Intercom Power Supply', labor_hours_per_unit: 0.5, system: 'ACCESS CONTROL', category: 'Intercom' },
    // --- Misc ---
    { name: 'Visitor Management Kiosk', labor_hours_per_unit: 4, system: 'ACCESS CONTROL', category: 'Misc' },
    { name: 'Card Printer', labor_hours_per_unit: 1, system: 'ACCESS CONTROL', category: 'Misc' },
    { name: 'Surge Protector (AC panel)', labor_hours_per_unit: 0.25, system: 'ACCESS CONTROL', category: 'Misc' },
    { name: 'Tamper Switch', labor_hours_per_unit: 0.15, system: 'ACCESS CONTROL', category: 'Misc' },
    { name: 'End-of-Line Resistor', labor_hours_per_unit: 0.1, system: 'ACCESS CONTROL', category: 'Misc' },
];

// ============================================================
// 4. AUDIO/VISUAL (AV)
// ============================================================
const AV: MaterialItem[] = [
    // --- Speakers ---
    { name: 'Ceiling Speaker 70V 8"', labor_hours_per_unit: 0.5, system: 'AV', category: 'Speakers' },
    { name: 'Ceiling Speaker 70V 6"', labor_hours_per_unit: 0.5, system: 'AV', category: 'Speakers' },
    { name: 'Ceiling Speaker 70V 4"', labor_hours_per_unit: 0.5, system: 'AV', category: 'Speakers' },
    { name: 'Ceiling Speaker Low-Profile', labor_hours_per_unit: 0.5, system: 'AV', category: 'Speakers' },
    { name: 'Wall Mount Speaker 70V', labor_hours_per_unit: 0.75, system: 'AV', category: 'Speakers' },
    { name: 'Surface Mount Speaker Box', labor_hours_per_unit: 0.75, system: 'AV', category: 'Speakers' },
    { name: 'Outdoor Speaker 70V Weather-Rated', labor_hours_per_unit: 1, system: 'AV', category: 'Speakers' },
    { name: 'Pendant Speaker', labor_hours_per_unit: 0.75, system: 'AV', category: 'Speakers' },
    { name: 'Column Array Speaker', labor_hours_per_unit: 1.5, system: 'AV', category: 'Speakers' },
    { name: 'Subwoofer Ceiling', labor_hours_per_unit: 0.75, system: 'AV', category: 'Speakers' },
    { name: 'Subwoofer Floor/Wall', labor_hours_per_unit: 1, system: 'AV', category: 'Speakers' },
    { name: 'Horn Speaker Outdoor', labor_hours_per_unit: 0.75, system: 'AV', category: 'Speakers' },
    { name: 'Paging Horn Speaker', labor_hours_per_unit: 0.75, system: 'AV', category: 'Speakers' },
    { name: 'Speaker Back Can / Enclosure', labor_hours_per_unit: 0.25, system: 'AV', category: 'Speakers' },
    { name: 'Speaker Tile Bridge / Support', labor_hours_per_unit: 0.15, system: 'AV', category: 'Speakers' },
    { name: 'Speaker Volume Attenuator', labor_hours_per_unit: 0.25, system: 'AV', category: 'Speakers' },
    // --- Amplifiers & DSP ---
    { name: 'Amplifier 70V 120W', labor_hours_per_unit: 1, system: 'AV', category: 'Amplifiers' },
    { name: 'Amplifier 70V 240W', labor_hours_per_unit: 1.5, system: 'AV', category: 'Amplifiers' },
    { name: 'Amplifier 70V 500W', labor_hours_per_unit: 2, system: 'AV', category: 'Amplifiers' },
    { name: 'Multi-Zone Amplifier 4-Zone', labor_hours_per_unit: 2, system: 'AV', category: 'Amplifiers' },
    { name: 'Multi-Zone Amplifier 8-Zone', labor_hours_per_unit: 3, system: 'AV', category: 'Amplifiers' },
    { name: 'Network Amplifier (Dante/AES67)', labor_hours_per_unit: 2, system: 'AV', category: 'Amplifiers' },
    { name: 'DSP Processor', labor_hours_per_unit: 3, system: 'AV', category: 'Amplifiers' },
    { name: 'DSP Expansion Card', labor_hours_per_unit: 0.5, system: 'AV', category: 'Amplifiers' },
    { name: 'Audio Mixer 8-Channel', labor_hours_per_unit: 1.5, system: 'AV', category: 'Amplifiers' },
    { name: 'Audio Mixer 16-Channel', labor_hours_per_unit: 2, system: 'AV', category: 'Amplifiers' },
    { name: 'Paging Controller', labor_hours_per_unit: 2, system: 'AV', category: 'Amplifiers' },
    { name: 'Zone Paging Adapter', labor_hours_per_unit: 1, system: 'AV', category: 'Amplifiers' },
    // --- Displays ---
    { name: 'Commercial Display 43"', labor_hours_per_unit: 1.5, system: 'AV', category: 'Displays' },
    { name: 'Commercial Display 55"', labor_hours_per_unit: 2, system: 'AV', category: 'Displays' },
    { name: 'Commercial Display 65"', labor_hours_per_unit: 2.5, system: 'AV', category: 'Displays' },
    { name: 'Commercial Display 75"', labor_hours_per_unit: 3, system: 'AV', category: 'Displays' },
    { name: 'Commercial Display 86"', labor_hours_per_unit: 3.5, system: 'AV', category: 'Displays' },
    { name: 'Commercial Display 98"', labor_hours_per_unit: 4, system: 'AV', category: 'Displays' },
    { name: 'Video Wall Panel 55"', labor_hours_per_unit: 2, system: 'AV', category: 'Displays' },
    { name: 'LED Direct-View Wall Panel (per panel)', labor_hours_per_unit: 1, system: 'AV', category: 'Displays' },
    { name: 'Interactive Touch Display 55"', labor_hours_per_unit: 2.5, system: 'AV', category: 'Displays' },
    { name: 'Interactive Touch Display 75"', labor_hours_per_unit: 3, system: 'AV', category: 'Displays' },
    { name: 'Interactive Touch Display 86"', labor_hours_per_unit: 3.5, system: 'AV', category: 'Displays' },
    { name: 'Digital Signage Player', labor_hours_per_unit: 0.5, system: 'AV', category: 'Displays' },
    { name: 'Display Wall Mount Fixed', labor_hours_per_unit: 0.75, system: 'AV', category: 'Displays' },
    { name: 'Display Wall Mount Tilt', labor_hours_per_unit: 0.75, system: 'AV', category: 'Displays' },
    { name: 'Display Wall Mount Full-Motion', labor_hours_per_unit: 1, system: 'AV', category: 'Displays' },
    { name: 'Display Ceiling Mount', labor_hours_per_unit: 1.5, system: 'AV', category: 'Displays' },
    { name: 'Display Floor Stand / Cart', labor_hours_per_unit: 0.75, system: 'AV', category: 'Displays' },
    { name: 'Display Recessed Wall NIche', labor_hours_per_unit: 4, system: 'AV', category: 'Displays' },
    // --- Projectors ---
    { name: 'Projector Short-Throw', labor_hours_per_unit: 2, system: 'AV', category: 'Projectors' },
    { name: 'Projector Long-Throw', labor_hours_per_unit: 2, system: 'AV', category: 'Projectors' },
    { name: 'Projector Ultra-Short-Throw', labor_hours_per_unit: 2.5, system: 'AV', category: 'Projectors' },
    { name: 'Projector Laser 4K', labor_hours_per_unit: 3, system: 'AV', category: 'Projectors' },
    { name: 'Projector Ceiling Mount', labor_hours_per_unit: 1, system: 'AV', category: 'Projectors' },
    { name: 'Projector Mount Pipe Extension', labor_hours_per_unit: 0.5, system: 'AV', category: 'Projectors' },
    { name: 'Projector Screen Motorized 100"', labor_hours_per_unit: 2, system: 'AV', category: 'Projectors' },
    { name: 'Projector Screen Motorized 120"', labor_hours_per_unit: 2.5, system: 'AV', category: 'Projectors' },
    { name: 'Projector Screen Fixed Frame 100"', labor_hours_per_unit: 1.5, system: 'AV', category: 'Projectors' },
    { name: 'Projector Screen Manual Pull-Down', labor_hours_per_unit: 1, system: 'AV', category: 'Projectors' },
    // --- Conferencing ---
    { name: 'Conferencing Codec (Zoom/Teams)', labor_hours_per_unit: 2, system: 'AV', category: 'Conferencing' },
    { name: 'USB Conference Camera', labor_hours_per_unit: 0.75, system: 'AV', category: 'Conferencing' },
    { name: 'PTZ Conference Camera', labor_hours_per_unit: 1.5, system: 'AV', category: 'Conferencing' },
    { name: 'Conference Camera Auto-Tracking', labor_hours_per_unit: 2, system: 'AV', category: 'Conferencing' },
    { name: 'Ceiling Microphone Array', labor_hours_per_unit: 1.5, system: 'AV', category: 'Conferencing' },
    { name: 'Table Boundary Microphone', labor_hours_per_unit: 0.25, system: 'AV', category: 'Conferencing' },
    { name: 'Gooseneck Microphone', labor_hours_per_unit: 0.25, system: 'AV', category: 'Conferencing' },
    { name: 'Wireless Microphone System', labor_hours_per_unit: 1, system: 'AV', category: 'Conferencing' },
    { name: 'Lavalier / Lapel Microphone', labor_hours_per_unit: 0.15, system: 'AV', category: 'Conferencing' },
    { name: 'Conference Speakerphone', labor_hours_per_unit: 0.5, system: 'AV', category: 'Conferencing' },
    { name: 'Conference Room Soundbar', labor_hours_per_unit: 1, system: 'AV', category: 'Conferencing' },
    { name: 'USB Soundbar + Camera Combo', labor_hours_per_unit: 1, system: 'AV', category: 'Conferencing' },
    { name: 'Conference Room Scheduling Panel', labor_hours_per_unit: 1, system: 'AV', category: 'Conferencing' },
    { name: 'Wireless Presentation Device', labor_hours_per_unit: 0.5, system: 'AV', category: 'Conferencing' },
    // --- Video Distribution ---
    { name: 'HDMI Switcher 4x1', labor_hours_per_unit: 0.5, system: 'AV', category: 'Distribution' },
    { name: 'HDMI Switcher 8x1', labor_hours_per_unit: 0.75, system: 'AV', category: 'Distribution' },
    { name: 'HDMI Matrix Switcher 4x4', labor_hours_per_unit: 1.5, system: 'AV', category: 'Distribution' },
    { name: 'HDMI Matrix Switcher 8x8', labor_hours_per_unit: 2, system: 'AV', category: 'Distribution' },
    { name: 'HDMI Matrix Switcher 16x16', labor_hours_per_unit: 3, system: 'AV', category: 'Distribution' },
    { name: 'HDMI Splitter 1x4', labor_hours_per_unit: 0.25, system: 'AV', category: 'Distribution' },
    { name: 'HDMI Splitter 1x8', labor_hours_per_unit: 0.5, system: 'AV', category: 'Distribution' },
    { name: 'HDMI Over Cat6 Extender Pair', labor_hours_per_unit: 0.5, system: 'AV', category: 'Distribution' },
    { name: 'HDMI Over Fiber Extender Pair', labor_hours_per_unit: 0.75, system: 'AV', category: 'Distribution' },
    { name: 'HDBaseT Transmitter', labor_hours_per_unit: 0.5, system: 'AV', category: 'Distribution' },
    { name: 'HDBaseT Receiver', labor_hours_per_unit: 0.5, system: 'AV', category: 'Distribution' },
    { name: 'AV-over-IP Encoder', labor_hours_per_unit: 0.75, system: 'AV', category: 'Distribution' },
    { name: 'AV-over-IP Decoder', labor_hours_per_unit: 0.75, system: 'AV', category: 'Distribution' },
    { name: 'Dante Network Audio Transmitter', labor_hours_per_unit: 0.75, system: 'AV', category: 'Distribution' },
    { name: 'Dante Network Audio Receiver', labor_hours_per_unit: 0.75, system: 'AV', category: 'Distribution' },
    // --- Control Systems ---
    { name: 'Control Processor (Crestron/Extron/QSC)', labor_hours_per_unit: 4, system: 'AV', category: 'Control' },
    { name: 'Touch Panel Controller 7"', labor_hours_per_unit: 1.5, system: 'AV', category: 'Control' },
    { name: 'Touch Panel Controller 10"', labor_hours_per_unit: 1.5, system: 'AV', category: 'Control' },
    { name: 'Wall Plate Controller / Button Panel', labor_hours_per_unit: 0.75, system: 'AV', category: 'Control' },
    { name: 'Occupancy Sensor (AV Auto-On)', labor_hours_per_unit: 0.5, system: 'AV', category: 'Control' },
    { name: 'IR Emitter / Sensor', labor_hours_per_unit: 0.25, system: 'AV', category: 'Control' },
    { name: 'Control System Programming (per room)', labor_hours_per_unit: 8, system: 'AV', category: 'Control' },
    // --- AV Cable ---
    { name: '18/2 Speaker Wire (1000ft)', labor_hours_per_unit: 4, system: 'AV', category: 'Cable' },
    { name: '16/2 Speaker Wire (1000ft)', labor_hours_per_unit: 4, system: 'AV', category: 'Cable' },
    { name: '14/2 Speaker Wire (1000ft)', labor_hours_per_unit: 4.5, system: 'AV', category: 'Cable' },
    { name: 'HDMI Cable 6ft', labor_hours_per_unit: 0.1, system: 'AV', category: 'Cable' },
    { name: 'HDMI Cable 15ft', labor_hours_per_unit: 0.1, system: 'AV', category: 'Cable' },
    { name: 'HDMI Cable 25ft Active', labor_hours_per_unit: 0.15, system: 'AV', category: 'Cable' },
    { name: 'HDMI AOC (Active Optical) 50ft', labor_hours_per_unit: 0.2, system: 'AV', category: 'Cable' },
    { name: 'HDMI AOC (Active Optical) 100ft', labor_hours_per_unit: 0.25, system: 'AV', category: 'Cable' },
    { name: 'DisplayPort Cable 6ft', labor_hours_per_unit: 0.1, system: 'AV', category: 'Cable' },
    { name: 'USB-C Cable 6ft', labor_hours_per_unit: 0.1, system: 'AV', category: 'Cable' },
    { name: 'USB Extension Over Cat6', labor_hours_per_unit: 0.35, system: 'AV', category: 'Cable' },
    { name: 'XLR Microphone Cable 25ft', labor_hours_per_unit: 0.1, system: 'AV', category: 'Cable' },
    { name: 'Cat6 for AV-over-IP (1000ft)', labor_hours_per_unit: 5, system: 'AV', category: 'Cable' },
    { name: '3.5mm Aux Cable 6ft', labor_hours_per_unit: 0.05, system: 'AV', category: 'Cable' },
    { name: 'Plenum-Rated HDMI (25ft)', labor_hours_per_unit: 0.2, system: 'AV', category: 'Cable' },
    // --- AV Furniture / Infrastructure ---
    { name: 'AV Rack Credenza / AV Cart', labor_hours_per_unit: 2, system: 'AV', category: 'Furniture' },
    { name: 'AV Equipment Shelf (rack mount)', labor_hours_per_unit: 0.25, system: 'AV', category: 'Furniture' },
    { name: 'In-Table AV Connection Box', labor_hours_per_unit: 1.5, system: 'AV', category: 'Furniture' },
    { name: 'Floor Box AV (HDMI+Power)', labor_hours_per_unit: 2, system: 'AV', category: 'Furniture' },
    { name: 'AV Wall Plate (HDMI+USB)', labor_hours_per_unit: 0.3, system: 'AV', category: 'Furniture' },
    { name: 'Cable Cubby / Table Pop-Up', labor_hours_per_unit: 1, system: 'AV', category: 'Furniture' },
    { name: 'Lectern / Podium (with AV)', labor_hours_per_unit: 4, system: 'AV', category: 'Furniture' },
    { name: 'AV Rack Cooling Fan', labor_hours_per_unit: 0.25, system: 'AV', category: 'Furniture' },
];

// ============================================================
// 5. INTRUSION DETECTION
// ============================================================
const INTRUSION: MaterialItem[] = [
    // --- Detection Devices ---
    { name: 'PIR Motion Detector Wall Mount', labor_hours_per_unit: 0.5, system: 'INTRUSION', category: 'Detectors' },
    { name: 'PIR Motion Detector Ceiling Mount', labor_hours_per_unit: 0.5, system: 'INTRUSION', category: 'Detectors' },
    { name: 'Dual-Tech Motion Detector (PIR+MW)', labor_hours_per_unit: 0.5, system: 'INTRUSION', category: 'Detectors' },
    { name: 'PIR Motion Detector Pet-Immune', labor_hours_per_unit: 0.5, system: 'INTRUSION', category: 'Detectors' },
    { name: 'PIR Motion Detector Long-Range', labor_hours_per_unit: 0.5, system: 'INTRUSION', category: 'Detectors' },
    { name: 'PIR Motion Detector Curtain (narrow)', labor_hours_per_unit: 0.5, system: 'INTRUSION', category: 'Detectors' },
    { name: 'Outdoor PIR Detector', labor_hours_per_unit: 0.75, system: 'INTRUSION', category: 'Detectors' },
    { name: 'Outdoor Dual-Tech Detector', labor_hours_per_unit: 0.75, system: 'INTRUSION', category: 'Detectors' },
    { name: 'Microwave Motion Detector', labor_hours_per_unit: 0.5, system: 'INTRUSION', category: 'Detectors' },
    { name: 'Glass Break Detector', labor_hours_per_unit: 0.3, system: 'INTRUSION', category: 'Detectors' },
    { name: 'Glass Break Detector Ceiling Mount', labor_hours_per_unit: 0.35, system: 'INTRUSION', category: 'Detectors' },
    { name: 'Acoustic Glass Break Sensor', labor_hours_per_unit: 0.3, system: 'INTRUSION', category: 'Detectors' },
    { name: 'Shock / Vibration Sensor', labor_hours_per_unit: 0.35, system: 'INTRUSION', category: 'Detectors' },
    { name: 'Beam Detector (Photoelectric Pair)', labor_hours_per_unit: 1.5, system: 'INTRUSION', category: 'Detectors' },
    { name: 'Beam Detector Reflective', labor_hours_per_unit: 1, system: 'INTRUSION', category: 'Detectors' },
    { name: 'Beam Detector Multi-Beam Stack', labor_hours_per_unit: 2, system: 'INTRUSION', category: 'Detectors' },
    { name: 'Fence Sensor (per zone)', labor_hours_per_unit: 4, system: 'INTRUSION', category: 'Detectors' },
    { name: 'Buried Sensor Cable (per 100ft)', labor_hours_per_unit: 6, system: 'INTRUSION', category: 'Detectors' },
    { name: 'Video Analytics Sensor', labor_hours_per_unit: 1, system: 'INTRUSION', category: 'Detectors' },
    // --- Door/Window Contacts ---
    { name: 'Surface Mount Door Contact', labor_hours_per_unit: 0.25, system: 'INTRUSION', category: 'Contacts' },
    { name: 'Recessed Door Contact', labor_hours_per_unit: 0.4, system: 'INTRUSION', category: 'Contacts' },
    { name: 'Wide-Gap Door Contact', labor_hours_per_unit: 0.3, system: 'INTRUSION', category: 'Contacts' },
    { name: 'Overhead/Roll-Up Door Contact', labor_hours_per_unit: 0.5, system: 'INTRUSION', category: 'Contacts' },
    { name: 'Window Contact', labor_hours_per_unit: 0.25, system: 'INTRUSION', category: 'Contacts' },
    { name: 'Heavy-Duty Contact (Steel Door)', labor_hours_per_unit: 0.4, system: 'INTRUSION', category: 'Contacts' },
    { name: 'Recessed Floor Contact', labor_hours_per_unit: 0.5, system: 'INTRUSION', category: 'Contacts' },
    { name: 'Contact Spacer/Magnet', labor_hours_per_unit: 0.05, system: 'INTRUSION', category: 'Contacts' },
    // --- Panels & Keypads ---
    { name: 'Intrusion Panel 8-Zone', labor_hours_per_unit: 3, system: 'INTRUSION', category: 'Panels' },
    { name: 'Intrusion Panel 16-Zone', labor_hours_per_unit: 4, system: 'INTRUSION', category: 'Panels' },
    { name: 'Intrusion Panel 32-Zone', labor_hours_per_unit: 5, system: 'INTRUSION', category: 'Panels' },
    { name: 'Intrusion Panel 64-Zone', labor_hours_per_unit: 6, system: 'INTRUSION', category: 'Panels' },
    { name: 'Intrusion Panel 128-Zone Enterprise', labor_hours_per_unit: 8, system: 'INTRUSION', category: 'Panels' },
    { name: 'Zone Expansion Module (8-zone)', labor_hours_per_unit: 1.5, system: 'INTRUSION', category: 'Panels' },
    { name: 'Zone Expansion Module (16-zone)', labor_hours_per_unit: 2, system: 'INTRUSION', category: 'Panels' },
    { name: 'Keypad LCD Alpha', labor_hours_per_unit: 0.5, system: 'INTRUSION', category: 'Keypads' },
    { name: 'Keypad Touchscreen', labor_hours_per_unit: 0.75, system: 'INTRUSION', category: 'Keypads' },
    { name: 'Keypad LED (Basic)', labor_hours_per_unit: 0.4, system: 'INTRUSION', category: 'Keypads' },
    { name: 'Keypad with Prox Reader', labor_hours_per_unit: 0.75, system: 'INTRUSION', category: 'Keypads' },
    { name: 'Annunciator Panel', labor_hours_per_unit: 1.5, system: 'INTRUSION', category: 'Keypads' },
    { name: 'Remote Arming Station', labor_hours_per_unit: 0.5, system: 'INTRUSION', category: 'Keypads' },
    // --- Notification ---
    { name: 'Interior Siren', labor_hours_per_unit: 0.35, system: 'INTRUSION', category: 'Notification' },
    { name: 'Exterior Siren (Weatherproof)', labor_hours_per_unit: 0.5, system: 'INTRUSION', category: 'Notification' },
    { name: 'Strobe Light Interior', labor_hours_per_unit: 0.3, system: 'INTRUSION', category: 'Notification' },
    { name: 'Siren/Strobe Combo Interior', labor_hours_per_unit: 0.4, system: 'INTRUSION', category: 'Notification' },
    { name: 'Siren/Strobe Combo Exterior', labor_hours_per_unit: 0.5, system: 'INTRUSION', category: 'Notification' },
    { name: 'Panic / Duress Button', labor_hours_per_unit: 0.25, system: 'INTRUSION', category: 'Notification' },
    { name: 'Hold-Up Button (Under-Desk)', labor_hours_per_unit: 0.3, system: 'INTRUSION', category: 'Notification' },
    { name: 'Money Clip / Bill Trap', labor_hours_per_unit: 0.3, system: 'INTRUSION', category: 'Notification' },
    // --- Communication ---
    { name: 'Cellular Communicator (Alarm)', labor_hours_per_unit: 0.5, system: 'INTRUSION', category: 'Communication' },
    { name: 'IP Communicator Module', labor_hours_per_unit: 0.5, system: 'INTRUSION', category: 'Communication' },
    { name: 'Dual-Path Communicator (IP+Cell)', labor_hours_per_unit: 0.75, system: 'INTRUSION', category: 'Communication' },
    { name: 'DACT (Digital Alarm Communicator)', labor_hours_per_unit: 0.5, system: 'INTRUSION', category: 'Communication' },
    { name: 'Central Station Receiver', labor_hours_per_unit: 2, system: 'INTRUSION', category: 'Communication' },
    // --- Intrusion Cable & Power ---
    { name: '22/4 Alarm Cable (1000ft)', labor_hours_per_unit: 4, system: 'INTRUSION', category: 'Cable' },
    { name: '22/2 Alarm Cable (1000ft)', labor_hours_per_unit: 3.5, system: 'INTRUSION', category: 'Cable' },
    { name: '18/4 Alarm Cable (1000ft)', labor_hours_per_unit: 4.5, system: 'INTRUSION', category: 'Cable' },
    { name: '22/6 Alarm Cable (1000ft)', labor_hours_per_unit: 4.5, system: 'INTRUSION', category: 'Cable' },
    { name: 'Intrusion Panel Battery 12V 7Ah', labor_hours_per_unit: 0.15, system: 'INTRUSION', category: 'Power' },
    { name: 'Intrusion Panel Battery 12V 18Ah', labor_hours_per_unit: 0.2, system: 'INTRUSION', category: 'Power' },
    { name: 'Intrusion Transformer 16.5VAC', labor_hours_per_unit: 0.25, system: 'INTRUSION', category: 'Power' },
    { name: 'Intrusion Power Supply 12VDC', labor_hours_per_unit: 0.5, system: 'INTRUSION', category: 'Power' },
    { name: 'End-of-Line Resistor Kit', labor_hours_per_unit: 0.1, system: 'INTRUSION', category: 'Power' },
    // --- Wireless ---
    { name: 'Wireless Motion Detector', labor_hours_per_unit: 0.3, system: 'INTRUSION', category: 'Wireless' },
    { name: 'Wireless Door Contact', labor_hours_per_unit: 0.2, system: 'INTRUSION', category: 'Wireless' },
    { name: 'Wireless Glass Break', labor_hours_per_unit: 0.2, system: 'INTRUSION', category: 'Wireless' },
    { name: 'Wireless Receiver Module', labor_hours_per_unit: 0.5, system: 'INTRUSION', category: 'Wireless' },
    { name: 'Wireless Key Fob', labor_hours_per_unit: 0.1, system: 'INTRUSION', category: 'Wireless' },
    { name: 'Wireless Repeater', labor_hours_per_unit: 0.25, system: 'INTRUSION', category: 'Wireless' },
    { name: 'Wireless Smoke Detector', labor_hours_per_unit: 0.25, system: 'INTRUSION', category: 'Wireless' },
    { name: 'Wireless Panic Button', labor_hours_per_unit: 0.15, system: 'INTRUSION', category: 'Wireless' },
    // --- Environmental ---
    { name: 'Water Leak Sensor', labor_hours_per_unit: 0.25, system: 'INTRUSION', category: 'Environmental' },
    { name: 'Temperature Sensor', labor_hours_per_unit: 0.25, system: 'INTRUSION', category: 'Environmental' },
    { name: 'Humidity Sensor', labor_hours_per_unit: 0.25, system: 'INTRUSION', category: 'Environmental' },
    { name: 'CO Detector (Intrusion Monitored)', labor_hours_per_unit: 0.35, system: 'INTRUSION', category: 'Environmental' },
    { name: 'Flood Rope Sensor (per 25ft)', labor_hours_per_unit: 0.5, system: 'INTRUSION', category: 'Environmental' },
];

// ============================================================
// 6. FIRE ALARM
// ============================================================
const FIRE_ALARM: MaterialItem[] = [
    // --- Detection ---
    { name: 'Smoke Detector Photoelectric', labor_hours_per_unit: 0.35, system: 'FIRE ALARM', category: 'Detection' },
    { name: 'Smoke Detector Ionization', labor_hours_per_unit: 0.35, system: 'FIRE ALARM', category: 'Detection' },
    { name: 'Smoke Detector Multi-Criteria', labor_hours_per_unit: 0.4, system: 'FIRE ALARM', category: 'Detection' },
    { name: 'Heat Detector Fixed-Temperature', labor_hours_per_unit: 0.35, system: 'FIRE ALARM', category: 'Detection' },
    { name: 'Heat Detector Rate-of-Rise', labor_hours_per_unit: 0.35, system: 'FIRE ALARM', category: 'Detection' },
    { name: 'Heat Detector Combo (Fixed+ROR)', labor_hours_per_unit: 0.35, system: 'FIRE ALARM', category: 'Detection' },
    { name: 'Duct Smoke Detector', labor_hours_per_unit: 1.5, system: 'FIRE ALARM', category: 'Detection' },
    { name: 'Duct Detector Housing', labor_hours_per_unit: 0.5, system: 'FIRE ALARM', category: 'Detection' },
    { name: 'Duct Detector Sampling Tube Kit', labor_hours_per_unit: 0.5, system: 'FIRE ALARM', category: 'Detection' },
    { name: 'Beam Smoke Detector (Projected)', labor_hours_per_unit: 2, system: 'FIRE ALARM', category: 'Detection' },
    { name: 'Beam Detector Reflector', labor_hours_per_unit: 0.5, system: 'FIRE ALARM', category: 'Detection' },
    { name: 'Air Sampling/Aspirating Detector (VESDA)', labor_hours_per_unit: 4, system: 'FIRE ALARM', category: 'Detection' },
    { name: 'VESDA Sampling Pipe (per 100ft)', labor_hours_per_unit: 2, system: 'FIRE ALARM', category: 'Detection' },
    { name: 'Flame Detector (UV/IR)', labor_hours_per_unit: 1.5, system: 'FIRE ALARM', category: 'Detection' },
    { name: 'CO Detector (Fire Alarm System)', labor_hours_per_unit: 0.35, system: 'FIRE ALARM', category: 'Detection' },
    { name: 'Combination Smoke/CO Detector', labor_hours_per_unit: 0.4, system: 'FIRE ALARM', category: 'Detection' },
    { name: 'Linear Heat Detection Cable (per 100ft)', labor_hours_per_unit: 2, system: 'FIRE ALARM', category: 'Detection' },
    { name: 'Smoke Detector Base (Standard)', labor_hours_per_unit: 0.1, system: 'FIRE ALARM', category: 'Detection' },
    { name: 'Smoke Detector Base (Relay)', labor_hours_per_unit: 0.15, system: 'FIRE ALARM', category: 'Detection' },
    { name: 'Smoke Detector Base (Sounder)', labor_hours_per_unit: 0.15, system: 'FIRE ALARM', category: 'Detection' },
    { name: 'Smoke Detector Base (Isolator)', labor_hours_per_unit: 0.15, system: 'FIRE ALARM', category: 'Detection' },
    // --- Notification ---
    { name: 'Horn/Strobe Wall Mount', labor_hours_per_unit: 0.4, system: 'FIRE ALARM', category: 'Notification' },
    { name: 'Horn/Strobe Ceiling Mount', labor_hours_per_unit: 0.45, system: 'FIRE ALARM', category: 'Notification' },
    { name: 'Horn Wall Mount', labor_hours_per_unit: 0.35, system: 'FIRE ALARM', category: 'Notification' },
    { name: 'Strobe Wall Mount', labor_hours_per_unit: 0.35, system: 'FIRE ALARM', category: 'Notification' },
    { name: 'Strobe Ceiling Mount', labor_hours_per_unit: 0.4, system: 'FIRE ALARM', category: 'Notification' },
    { name: 'Chime/Strobe', labor_hours_per_unit: 0.4, system: 'FIRE ALARM', category: 'Notification' },
    { name: 'Speaker/Strobe Wall Mount', labor_hours_per_unit: 0.5, system: 'FIRE ALARM', category: 'Notification' },
    { name: 'Speaker/Strobe Ceiling Mount', labor_hours_per_unit: 0.55, system: 'FIRE ALARM', category: 'Notification' },
    { name: 'Speaker Wall Mount', labor_hours_per_unit: 0.4, system: 'FIRE ALARM', category: 'Notification' },
    { name: 'Outdoor Horn/Strobe (Weatherproof)', labor_hours_per_unit: 0.6, system: 'FIRE ALARM', category: 'Notification' },
    { name: 'Mini Horn/Strobe', labor_hours_per_unit: 0.35, system: 'FIRE ALARM', category: 'Notification' },
    { name: 'Fire Alarm Bell 6"', labor_hours_per_unit: 0.4, system: 'FIRE ALARM', category: 'Notification' },
    { name: 'Fire Alarm Bell 10"', labor_hours_per_unit: 0.5, system: 'FIRE ALARM', category: 'Notification' },
    // --- Initiating Devices ---
    { name: 'Manual Pull Station (Single-Action)', labor_hours_per_unit: 0.5, system: 'FIRE ALARM', category: 'Initiating' },
    { name: 'Manual Pull Station (Dual-Action)', labor_hours_per_unit: 0.5, system: 'FIRE ALARM', category: 'Initiating' },
    { name: 'Pull Station Guard Cover', labor_hours_per_unit: 0.1, system: 'FIRE ALARM', category: 'Initiating' },
    { name: 'Waterflow Switch (Sprinkler)', labor_hours_per_unit: 1, system: 'FIRE ALARM', category: 'Initiating' },
    { name: 'Tamper Switch (Valve)', labor_hours_per_unit: 0.5, system: 'FIRE ALARM', category: 'Initiating' },
    { name: 'Pressure Switch', labor_hours_per_unit: 0.5, system: 'FIRE ALARM', category: 'Initiating' },
    { name: 'Sprinkler System Monitor Module', labor_hours_per_unit: 0.5, system: 'FIRE ALARM', category: 'Initiating' },
    // --- Control Panels ---
    { name: 'Fire Alarm Control Panel (FACP) Small', labor_hours_per_unit: 8, system: 'FIRE ALARM', category: 'Panels' },
    { name: 'Fire Alarm Control Panel (FACP) Medium', labor_hours_per_unit: 12, system: 'FIRE ALARM', category: 'Panels' },
    { name: 'Fire Alarm Control Panel (FACP) Large', labor_hours_per_unit: 16, system: 'FIRE ALARM', category: 'Panels' },
    { name: 'Fire Alarm Network Panel (Node)', labor_hours_per_unit: 6, system: 'FIRE ALARM', category: 'Panels' },
    { name: 'Remote Annunciator Panel', labor_hours_per_unit: 2, system: 'FIRE ALARM', category: 'Panels' },
    { name: 'Graphic Annunciator', labor_hours_per_unit: 4, system: 'FIRE ALARM', category: 'Panels' },
    { name: 'Fire Alarm Power Supply (Booster)', labor_hours_per_unit: 2, system: 'FIRE ALARM', category: 'Panels' },
    { name: 'Battery 12V 7Ah (Fire Alarm)', labor_hours_per_unit: 0.15, system: 'FIRE ALARM', category: 'Panels' },
    { name: 'Battery 12V 18Ah (Fire Alarm)', labor_hours_per_unit: 0.2, system: 'FIRE ALARM', category: 'Panels' },
    { name: 'Battery 12V 55Ah (Fire Alarm)', labor_hours_per_unit: 0.25, system: 'FIRE ALARM', category: 'Panels' },
    // --- Modules ---
    { name: 'Monitor Module (Addressable)', labor_hours_per_unit: 0.35, system: 'FIRE ALARM', category: 'Modules' },
    { name: 'Control Module (Addressable)', labor_hours_per_unit: 0.35, system: 'FIRE ALARM', category: 'Modules' },
    { name: 'Mini Monitor Module', labor_hours_per_unit: 0.25, system: 'FIRE ALARM', category: 'Modules' },
    { name: 'Relay Module', labor_hours_per_unit: 0.35, system: 'FIRE ALARM', category: 'Modules' },
    { name: 'Isolator Module', labor_hours_per_unit: 0.3, system: 'FIRE ALARM', category: 'Modules' },
    { name: 'IAM (Intelligent Addressable Module)', labor_hours_per_unit: 0.35, system: 'FIRE ALARM', category: 'Modules' },
    { name: 'Loop Expander Module', labor_hours_per_unit: 1.5, system: 'FIRE ALARM', category: 'Modules' },
    { name: 'Conventional Zone Module', labor_hours_per_unit: 0.5, system: 'FIRE ALARM', category: 'Modules' },
    // --- Fire Alarm Cable ---
    { name: 'Fire Alarm Cable 16/2 FPLP (1000ft)', labor_hours_per_unit: 5, system: 'FIRE ALARM', category: 'Cable' },
    { name: 'Fire Alarm Cable 14/2 FPLP (1000ft)', labor_hours_per_unit: 5.5, system: 'FIRE ALARM', category: 'Cable' },
    { name: 'Fire Alarm Cable 18/2 FPLP (1000ft)', labor_hours_per_unit: 4.5, system: 'FIRE ALARM', category: 'Cable' },
    { name: 'Fire Alarm Cable 16/4 FPLP (1000ft)', labor_hours_per_unit: 5.5, system: 'FIRE ALARM', category: 'Cable' },
    { name: 'Fire Alarm Cable 14/4 FPLP (1000ft)', labor_hours_per_unit: 6, system: 'FIRE ALARM', category: 'Cable' },
    { name: 'Fire Alarm Cable 18/4 FPLP (1000ft)', labor_hours_per_unit: 5, system: 'FIRE ALARM', category: 'Cable' },
    { name: 'Fire Alarm SLC Cable 18/2 Shielded (1000ft)', labor_hours_per_unit: 5, system: 'FIRE ALARM', category: 'Cable' },
    { name: 'Fire Alarm SLC Cable 16/2 Shielded (1000ft)', labor_hours_per_unit: 5.5, system: 'FIRE ALARM', category: 'Cable' },
    // --- Suppression Interface ---
    { name: 'Releasing Panel (Suppression)', labor_hours_per_unit: 8, system: 'FIRE ALARM', category: 'Suppression' },
    { name: 'Abort Switch', labor_hours_per_unit: 0.5, system: 'FIRE ALARM', category: 'Suppression' },
    { name: 'Pre-Action Valve Monitor', labor_hours_per_unit: 1, system: 'FIRE ALARM', category: 'Suppression' },
    { name: 'Releasing Solenoid', labor_hours_per_unit: 1, system: 'FIRE ALARM', category: 'Suppression' },
    { name: 'Door Holder (Fire Release)', labor_hours_per_unit: 0.75, system: 'FIRE ALARM', category: 'Suppression' },
    { name: 'Fire Damper Monitor', labor_hours_per_unit: 0.75, system: 'FIRE ALARM', category: 'Suppression' },
    { name: 'Elevator Recall Module', labor_hours_per_unit: 1.5, system: 'FIRE ALARM', category: 'Suppression' },
    { name: 'HVAC Shutdown Relay', labor_hours_per_unit: 0.75, system: 'FIRE ALARM', category: 'Suppression' },
    // --- Misc ---
    { name: 'Fire Alarm Red Paint (per room)', labor_hours_per_unit: 0.25, system: 'FIRE ALARM', category: 'Misc' },
    { name: 'Fire Alarm As-Built Drawings', labor_hours_per_unit: 8, system: 'FIRE ALARM', category: 'Misc' },
    { name: 'Fire Alarm Acceptance Test (per device)', labor_hours_per_unit: 0.15, system: 'FIRE ALARM', category: 'Misc' },
    { name: 'Fire Watch (per hour)', labor_hours_per_unit: 1, system: 'FIRE ALARM', category: 'Misc' },
    { name: 'Remote Fire Alarm Monitoring Setup', labor_hours_per_unit: 2, system: 'FIRE ALARM', category: 'Misc' },
];

// ============================================================
// 7. INFRASTRUCTURE & LABOR-RICH ITEMS
// ============================================================
const INFRASTRUCTURE: MaterialItem[] = [
    // --- Racks & Cabinets ---
    { name: '2-Post Equipment Rack 7ft', labor_hours_per_unit: 2, system: 'INFRASTRUCTURE', category: 'Racks' },
    { name: '4-Post Equipment Rack 7ft', labor_hours_per_unit: 3, system: 'INFRASTRUCTURE', category: 'Racks' },
    { name: 'Floor-Standing Cabinet 42U', labor_hours_per_unit: 4, system: 'INFRASTRUCTURE', category: 'Racks' },
    { name: 'Floor-Standing Cabinet 45U', labor_hours_per_unit: 4, system: 'INFRASTRUCTURE', category: 'Racks' },
    { name: 'Wall-Mount Cabinet 6U', labor_hours_per_unit: 1.5, system: 'INFRASTRUCTURE', category: 'Racks' },
    { name: 'Wall-Mount Cabinet 12U', labor_hours_per_unit: 2, system: 'INFRASTRUCTURE', category: 'Racks' },
    { name: 'Wall-Mount Cabinet 18U', labor_hours_per_unit: 2.5, system: 'INFRASTRUCTURE', category: 'Racks' },
    { name: 'Outdoor Equipment Cabinet (NEMA 4)', labor_hours_per_unit: 6, system: 'INFRASTRUCTURE', category: 'Racks' },
    { name: 'Rack Shelf 1U', labor_hours_per_unit: 0.15, system: 'INFRASTRUCTURE', category: 'Racks' },
    { name: 'Rack Shelf 2U', labor_hours_per_unit: 0.2, system: 'INFRASTRUCTURE', category: 'Racks' },
    { name: 'Rack Blanking Panel 1U', labor_hours_per_unit: 0.05, system: 'INFRASTRUCTURE', category: 'Racks' },
    { name: 'Rack Fan Tray', labor_hours_per_unit: 0.25, system: 'INFRASTRUCTURE', category: 'Racks' },
    { name: 'Rack Cage Nuts (bag of 50)', labor_hours_per_unit: 0.5, system: 'INFRASTRUCTURE', category: 'Racks' },
    // --- Conduit ---
    { name: 'EMT Conduit 3/4" (10ft)', labor_hours_per_unit: 0.35, system: 'INFRASTRUCTURE', category: 'Conduit' },
    { name: 'EMT Conduit 1" (10ft)', labor_hours_per_unit: 0.4, system: 'INFRASTRUCTURE', category: 'Conduit' },
    { name: 'EMT Conduit 1-1/4" (10ft)', labor_hours_per_unit: 0.5, system: 'INFRASTRUCTURE', category: 'Conduit' },
    { name: 'EMT Conduit 1-1/2" (10ft)', labor_hours_per_unit: 0.55, system: 'INFRASTRUCTURE', category: 'Conduit' },
    { name: 'EMT Conduit 2" (10ft)', labor_hours_per_unit: 0.65, system: 'INFRASTRUCTURE', category: 'Conduit' },
    { name: 'EMT Conduit 3" (10ft)', labor_hours_per_unit: 0.85, system: 'INFRASTRUCTURE', category: 'Conduit' },
    { name: 'EMT Conduit 4" (10ft)', labor_hours_per_unit: 1, system: 'INFRASTRUCTURE', category: 'Conduit' },
    { name: 'PVC Conduit 3/4" (10ft)', labor_hours_per_unit: 0.25, system: 'INFRASTRUCTURE', category: 'Conduit' },
    { name: 'PVC Conduit 1" (10ft)', labor_hours_per_unit: 0.3, system: 'INFRASTRUCTURE', category: 'Conduit' },
    { name: 'PVC Conduit 2" (10ft)', labor_hours_per_unit: 0.45, system: 'INFRASTRUCTURE', category: 'Conduit' },
    { name: 'PVC Conduit 4" (10ft)', labor_hours_per_unit: 0.65, system: 'INFRASTRUCTURE', category: 'Conduit' },
    { name: 'Flex Conduit 3/4" (100ft)', labor_hours_per_unit: 2.5, system: 'INFRASTRUCTURE', category: 'Conduit' },
    { name: 'Flex Conduit 1" (100ft)', labor_hours_per_unit: 3, system: 'INFRASTRUCTURE', category: 'Conduit' },
    { name: 'Liquidtight Flex 3/4" (100ft)', labor_hours_per_unit: 3, system: 'INFRASTRUCTURE', category: 'Conduit' },
    { name: 'Liquidtight Flex 1" (100ft)', labor_hours_per_unit: 3.5, system: 'INFRASTRUCTURE', category: 'Conduit' },
    { name: 'Rigid Metal Conduit 1" (10ft)', labor_hours_per_unit: 0.75, system: 'INFRASTRUCTURE', category: 'Conduit' },
    { name: 'Rigid Metal Conduit 2" (10ft)', labor_hours_per_unit: 1, system: 'INFRASTRUCTURE', category: 'Conduit' },
    { name: 'Conduit Connector EMT (each)', labor_hours_per_unit: 0.1, system: 'INFRASTRUCTURE', category: 'Conduit' },
    { name: 'Conduit Coupling EMT (each)', labor_hours_per_unit: 0.1, system: 'INFRASTRUCTURE', category: 'Conduit' },
    { name: 'Conduit Strap/Hanger (each)', labor_hours_per_unit: 0.1, system: 'INFRASTRUCTURE', category: 'Conduit' },
    { name: 'Conduit Body (LB/LL/LR)', labor_hours_per_unit: 0.25, system: 'INFRASTRUCTURE', category: 'Conduit' },
    // --- Firestopping ---
    { name: 'Firestop Putty Pad (each)', labor_hours_per_unit: 0.15, system: 'INFRASTRUCTURE', category: 'Firestopping' },
    { name: 'Firestop Caulk / Sealant (tube)', labor_hours_per_unit: 0.25, system: 'INFRASTRUCTURE', category: 'Firestopping' },
    { name: 'Firestop Pillow (each)', labor_hours_per_unit: 0.1, system: 'INFRASTRUCTURE', category: 'Firestopping' },
    { name: 'Firestop Sleeve/Collar (each)', labor_hours_per_unit: 0.35, system: 'INFRASTRUCTURE', category: 'Firestopping' },
    { name: 'Firestop Wall Penetration (per opening)', labor_hours_per_unit: 0.5, system: 'INFRASTRUCTURE', category: 'Firestopping' },
    { name: 'Firestop Floor Penetration (per opening)', labor_hours_per_unit: 0.75, system: 'INFRASTRUCTURE', category: 'Firestopping' },
    { name: 'Firestop Multi-Cable Transit (MCT)', labor_hours_per_unit: 1.5, system: 'INFRASTRUCTURE', category: 'Firestopping' },
    // ==========================================
    // LABOR-RICH ITEMS (high hours per unit)
    // ==========================================
    // --- Trenching & Excavation ---
    { name: 'Trenching (per linear foot) - Dirt/Soil', labor_hours_per_unit: 0.25, system: 'INFRASTRUCTURE', category: 'Trenching' },
    { name: 'Trenching (per linear foot) - Asphalt', labor_hours_per_unit: 0.5, system: 'INFRASTRUCTURE', category: 'Trenching' },
    { name: 'Trenching (per linear foot) - Concrete', labor_hours_per_unit: 0.75, system: 'INFRASTRUCTURE', category: 'Trenching' },
    { name: 'Trenching (per linear foot) - Rock', labor_hours_per_unit: 1, system: 'INFRASTRUCTURE', category: 'Trenching' },
    { name: 'Backfill & Compaction (per linear foot)', labor_hours_per_unit: 0.15, system: 'INFRASTRUCTURE', category: 'Trenching' },
    { name: 'Underground Directional Bore (per linear foot)', labor_hours_per_unit: 0.5, system: 'INFRASTRUCTURE', category: 'Trenching' },
    { name: 'Concrete Sawcutting (per linear foot)', labor_hours_per_unit: 0.25, system: 'INFRASTRUCTURE', category: 'Trenching' },
    { name: 'Asphalt Patching (per square foot)', labor_hours_per_unit: 0.15, system: 'INFRASTRUCTURE', category: 'Trenching' },
    { name: 'Concrete Restoration (per square foot)', labor_hours_per_unit: 0.25, system: 'INFRASTRUCTURE', category: 'Trenching' },
    { name: 'Underground Conduit PVC 2" (per 100ft, installed)', labor_hours_per_unit: 8, system: 'INFRASTRUCTURE', category: 'Trenching' },
    { name: 'Underground Conduit PVC 4" (per 100ft, installed)', labor_hours_per_unit: 12, system: 'INFRASTRUCTURE', category: 'Trenching' },
    { name: 'Direct Burial Cable Warning Tape (per 1000ft)', labor_hours_per_unit: 0.5, system: 'INFRASTRUCTURE', category: 'Trenching' },
    { name: 'Underground Handhole / Pull Box', labor_hours_per_unit: 4, system: 'INFRASTRUCTURE', category: 'Trenching' },
    // --- Core Drilling & Penetrations ---
    { name: 'Core Drill 1" (per hole - concrete)', labor_hours_per_unit: 0.5, system: 'INFRASTRUCTURE', category: 'Core Drilling' },
    { name: 'Core Drill 2" (per hole - concrete)', labor_hours_per_unit: 0.75, system: 'INFRASTRUCTURE', category: 'Core Drilling' },
    { name: 'Core Drill 3" (per hole - concrete)', labor_hours_per_unit: 1, system: 'INFRASTRUCTURE', category: 'Core Drilling' },
    { name: 'Core Drill 4" (per hole - concrete)', labor_hours_per_unit: 1.5, system: 'INFRASTRUCTURE', category: 'Core Drilling' },
    { name: 'Core Drill 6" (per hole - concrete)', labor_hours_per_unit: 2, system: 'INFRASTRUCTURE', category: 'Core Drilling' },
    { name: 'Wall Penetration (masonry/block)', labor_hours_per_unit: 0.75, system: 'INFRASTRUCTURE', category: 'Core Drilling' },
    { name: 'Wall Penetration (drywall)', labor_hours_per_unit: 0.25, system: 'INFRASTRUCTURE', category: 'Core Drilling' },
    { name: 'Floor Penetration (concrete slab)', labor_hours_per_unit: 1.5, system: 'INFRASTRUCTURE', category: 'Core Drilling' },
    { name: 'Roof Penetration & Seal', labor_hours_per_unit: 2, system: 'INFRASTRUCTURE', category: 'Core Drilling' },
    // --- Lift & Aerial Work ---
    { name: 'Scissor Lift Work (per hour)', labor_hours_per_unit: 1, system: 'INFRASTRUCTURE', category: 'Lift Work' },
    { name: 'Boom Lift / JLG Work (per hour)', labor_hours_per_unit: 1, system: 'INFRASTRUCTURE', category: 'Lift Work' },
    { name: 'Bucket Truck Work (per hour)', labor_hours_per_unit: 1, system: 'INFRASTRUCTURE', category: 'Lift Work' },
    { name: 'Work From A-Frame Ladder (per hour)', labor_hours_per_unit: 1, system: 'INFRASTRUCTURE', category: 'Lift Work' },
    { name: 'Scaffolding Setup/Teardown (per section)', labor_hours_per_unit: 2, system: 'INFRASTRUCTURE', category: 'Lift Work' },
    { name: 'Scaffolding Work (per hour)', labor_hours_per_unit: 1, system: 'INFRASTRUCTURE', category: 'Lift Work' },
    { name: 'Fall Protection Setup (per day)', labor_hours_per_unit: 1, system: 'INFRASTRUCTURE', category: 'Lift Work' },
    { name: 'High-Ceiling Install >15ft (per device labor adder)', labor_hours_per_unit: 0.5, system: 'INFRASTRUCTURE', category: 'Lift Work' },
    { name: 'High-Ceiling Install >25ft (per device labor adder)', labor_hours_per_unit: 1, system: 'INFRASTRUCTURE', category: 'Lift Work' },
    { name: 'High-Ceiling Install >35ft (per device labor adder)', labor_hours_per_unit: 1.5, system: 'INFRASTRUCTURE', category: 'Lift Work' },
    // --- Concrete & Structural ---
    { name: 'Concrete Anchor Drilling & Setting (per anchor)', labor_hours_per_unit: 0.2, system: 'INFRASTRUCTURE', category: 'Structural' },
    { name: 'Concrete Anchor Epoxy (per anchor)', labor_hours_per_unit: 0.3, system: 'INFRASTRUCTURE', category: 'Structural' },
    { name: 'Unistrut / Strut Channel (per 10ft)', labor_hours_per_unit: 0.5, system: 'INFRASTRUCTURE', category: 'Structural' },
    { name: 'Unistrut Mounting Bracket', labor_hours_per_unit: 0.15, system: 'INFRASTRUCTURE', category: 'Structural' },
    { name: 'Pole Base Mounting Plate', labor_hours_per_unit: 1, system: 'INFRASTRUCTURE', category: 'Structural' },
    { name: 'Concrete Pad/Footing (per cubic yard)', labor_hours_per_unit: 8, system: 'INFRASTRUCTURE', category: 'Structural' },
    // --- Site Work & Mobilization ---
    { name: 'Mobilization/Demobilization (per trip)', labor_hours_per_unit: 4, system: 'INFRASTRUCTURE', category: 'Site Work' },
    { name: 'Project Startup / Layout', labor_hours_per_unit: 8, system: 'INFRASTRUCTURE', category: 'Site Work' },
    { name: 'Project Closeout Documentation', labor_hours_per_unit: 16, system: 'INFRASTRUCTURE', category: 'Site Work' },
    { name: 'As-Built Drawing Updates', labor_hours_per_unit: 8, system: 'INFRASTRUCTURE', category: 'Site Work' },
    { name: 'System Testing & Commissioning (per system)', labor_hours_per_unit: 8, system: 'INFRASTRUCTURE', category: 'Site Work' },
    { name: 'End-User Training (per session)', labor_hours_per_unit: 4, system: 'INFRASTRUCTURE', category: 'Site Work' },
    { name: 'General Cleanup & Debris Removal (per day)', labor_hours_per_unit: 2, system: 'INFRASTRUCTURE', category: 'Site Work' },
    { name: 'Material Handling & Staging (per day)', labor_hours_per_unit: 4, system: 'INFRASTRUCTURE', category: 'Site Work' },
    { name: 'Dumpster / Waste Removal', labor_hours_per_unit: 1, system: 'INFRASTRUCTURE', category: 'Site Work' },
    // --- Ceiling Work ---
    { name: 'Ceiling Tile Removal & Replacement (per tile)', labor_hours_per_unit: 0.15, system: 'INFRASTRUCTURE', category: 'Ceiling Work' },
    { name: 'Hard Ceiling Access (cut & patch, per opening)', labor_hours_per_unit: 1, system: 'INFRASTRUCTURE', category: 'Ceiling Work' },
    { name: 'Access Panel Install (drywall ceiling)', labor_hours_per_unit: 1.5, system: 'INFRASTRUCTURE', category: 'Ceiling Work' },
    { name: 'Plaster Ceiling Patch (per opening)', labor_hours_per_unit: 1.5, system: 'INFRASTRUCTURE', category: 'Ceiling Work' },
    { name: 'Drywall Patch/Repair (per opening)', labor_hours_per_unit: 0.75, system: 'INFRASTRUCTURE', category: 'Ceiling Work' },
    // --- Painting & Finishing ---
    { name: 'Conduit Painting (per 10ft)', labor_hours_per_unit: 0.25, system: 'INFRASTRUCTURE', category: 'Finishing' },
    { name: 'Device Matching / Color Swap', labor_hours_per_unit: 0.1, system: 'INFRASTRUCTURE', category: 'Finishing' },
    { name: 'Touch-Up Paint (per room)', labor_hours_per_unit: 0.5, system: 'INFRASTRUCTURE', category: 'Finishing' },
];

export const MATERIALS_LIBRARY: MaterialItem[] = [
    ...STRUCTURED_CABLING,
    ...CCTV,
    ...ACCESS_CONTROL,
    ...AV,
    ...INTRUSION,
    ...FIRE_ALARM,
    ...INFRASTRUCTURE,
];

// System names for reference
export const SYSTEM_NAMES = [
    'STRUCTURED CABLING',
    'CCTV',
    'ACCESS CONTROL',
    'AV',
    'INTRUSION',
    'FIRE ALARM',
    'INFRASTRUCTURE',
] as const;

